Repository lumapps/design-system, pull requests merged in 2019-09, with the labels that each got.

#129 Fix/demo react break line
  webpack/react/mdx-demo-code-extractor/index.js
  webpack/react/mdx-loader/index.js
Labels: need: review-frontend

#131 fix(react-list): cast children as array when unique child
  demo/react/doc/product/components/list.mdx
  demo/react/doc/product/components/select.mdx
  src/components/expansion-panel/react/ExpansionPanel.tsx
  src/components/list/react/List.tsx
  src/components/side-navigation/react/SideNavigation.tsx
  src/components/side-navigation/react/SideNavigationItem.tsx
Labels: need: review-frontend

#133 fix(react-select): fix focus on input when closing
  src/components/select/react/Select.tsx
Labels: need: review-frontend

#143 feat(post-block): adding the react version of the post-block
  demo/angularjs/components/post-block/demo.html
  demo/react/doc/product/components/post-block.mdx
  src/components/post-block/angularjs/post-block.html
  src/components/post-block/angularjs/post-block_directive.js
  src/components/post-block/react/PostBlock.tsx
  src/components/post-block/style/lumapps/_index.scss
  src/react.index.ts
Labels: need: test

#156 fix(text-field): text field React class names to handle both input and textarea
  src/components/text-field/react/TextField.test.tsx
  src/components/text-field/react/TextField.tsx
  src/components/text-field/react/__snapshots__/TextField.test.tsx.snap
  webpack/react/props-loader/convertPropTable.js
  webpack/react/props-loader/convertPropTable.spec.js
Labels: need: review-frontend

#149 fix(react-select): fix chips markup
  src/components/select/react/Select.tsx
Labels: need: rebase

#147 fix(react): removed const enum so they can be imported as object
  src/components/expansion-panel/react/ExpansionPanel.tsx
  src/components/select/react/Select.tsx
  src/components/thumbnail/react/Thumbnail.tsx
  src/react.index.ts
  tslint.json
Labels: need: review-frontend

#152 feat(radio-button): add radio group component
  demo/angularjs/components/radio-button/partials/default.html
  demo/angularjs/components/radio-button/partials/helper.html
  src/angularjs.index.js
  src/components/radio-button/angularjs/radio-group_directive.js
  src/components/radio-button/react/RadioGroup.test.tsx
  src/components/radio-button/react/RadioGroup.tsx
  src/components/radio-button/react/__snapshots__/RadioGroup.test.tsx.snap
  src/components/radio-button/style/lumapps/_index.scss
Labels: need: test

#145 docs(radio-button): update from angular
  demo/react/doc/product/components/radio-button.mdx
  src/react.index.ts
Labels: need: merge, need: rebase

#162 feat(post-block): add the possibility of html injection in the text prop
  demo/react/doc/product/components/post-block.mdx
  src/components/post-block/react/PostBlock.tsx
Labels: need: review-frontend

#146 feat(button): add has background param
  demo/angularjs/components/editable-media/demo.html
  demo/react/components/button/default.tsx
  demo/react/components/button/disabled.tsx
  demo/react/components/button/dropdown.tsx
  demo/react/components/button/index.tsx
  demo/react/components/button/sizes.tsx
  demo/react/components/button/with-icons.tsx
  demo/react/doc/product/components/button.mdx
  demo/react/doc/product/components/popover.mdx
  demo/react/layout/DemoBlock.tsx
  demo/react/layout/Main.tsx
  src/components/button/angularjs/button_directive.js
  src/components/button/react/Button.test.tsx
  src/components/button/react/Button.tsx
  src/components/button/react/ButtonRoot.test.tsx
  src/components/button/react/ButtonRoot.tsx
  src/components/button/react/DropdownButton.test.tsx
  src/components/button/react/DropdownButton.tsx
  src/components/button/react/IconButton.test.tsx
  src/components/button/react/IconButton.tsx
  src/components/button/react/__snapshots__/Button.test.tsx.snap
  src/components/button/react/__snapshots__/ButtonRoot.test.tsx.snap
  src/components/button/react/__snapshots__/DropdownButton.test.tsx.snap
  src/components/button/react/__snapshots__/IconButton.test.tsx.snap
  src/components/button/style/lumapps/_index.scss
  src/components/expansion-panel/react/ExpansionPanel.tsx
  src/components/expansion-panel/react/__snapshots__/ExpansionPanel.test.tsx.snap
  src/components/icon/react/Icon.tsx
  src/components/lightbox/react/Lightbox.tsx
  src/components/slideshow/react/SlideshowControls.tsx
  src/react.index.ts
  webpack/react/props-loader/convertPropTable.spec.js
Labels: need: test

#160 fix(dropdown): fix onClose unnecessary calls
  src/components/dropdown/react/Dropdown.tsx
Labels: need: merge

#163 fix(demo): fix bug when using template string in React MDX demo block
  demo/react/doc/product/components/popover.mdx
  demo/react/doc/product/components/progress-tracker.mdx
  demo/react/doc/product/components/thumbnail.mdx
  webpack/react/mdx-demo-code-extractor/index.js
Labels: need: review-frontend

#111 feat(slider): react component
  demo/react/components/slider/default.tsx
  demo/react/components/slider/index.tsx
  demo/react/components/slider/nolabel.tsx
  demo/react/components/slider/precision.tsx
  demo/react/components/slider/style.css
  demo/react/components/slider/withsteps.tsx
  demo/react/doc/product/components/slider.mdx
  demo/react/layout/MainNav.tsx
  src/components/slider/react/Slider.tsx
  src/components/slider/style/lumapps/_index.scss
  src/core/react/hooks/useEventCallback.tsx
  src/core/style/lumx-theme-lumapps.scss
  src/react.index.ts
Labels: need: test

#165 Refactor/checkbox
  CHANGELOG.md
  demo/react/components/checkbox/default.tsx
  demo/react/components/checkbox/index.tsx
  demo/react/doc/product/components/checkbox.mdx
  src/components/checkbox/react/Checkbox.test.tsx
  src/components/checkbox/react/Checkbox.tsx
  src/components/checkbox/react/CheckboxHelper.test.tsx
  src/components/checkbox/react/CheckboxHelper.tsx
  src/components/checkbox/react/CheckboxLabel.test.tsx
  src/components/checkbox/react/CheckboxLabel.tsx
  src/components/checkbox/react/__snapshots__/Checkbox.test.tsx.snap
  src/components/checkbox/react/__snapshots__/CheckboxHelper.test.tsx.snap
  src/components/checkbox/react/__snapshots__/CheckboxLabel.test.tsx.snap
  src/react.index.ts
Labels: need: test
