Repository lumapps/design-system, pull requests merged in 2019-05, with the labels that each got.

#43 docs(typography)
  demo/angularjs/app.js
  demo/angularjs/foundations/typography/demo.html
  demo/angularjs/foundations/typography/doc.md
  demo/angularjs/foundations/typography/partials/typography.html
  demo/angularjs/layout/demo/demo-block.html
  demo/angularjs/layout/demo/demo-block_directive.js
  demo/angularjs/layout/main/main-content_directive.js
  demo/angularjs/layout/sub-nav/sub-nav.html
Labels: need: dev-frontend

#52 docs/colors
  demo/angularjs/app.js
  demo/angularjs/foundations/colors/controller.js
  demo/angularjs/foundations/colors/demo.html
  demo/angularjs/foundations/colors/doc.md
  demo/angularjs/foundations/typography/demo.html
  demo/angularjs/layout/demo/demo-block_directive.js
  demo/angularjs/layout/demo/demo-colors.html
  demo/angularjs/layout/demo/demo-colors_directive.js
  demo/angularjs/layout/demo/demo-grid_directive.js
  demo/angularjs/layout/sub-nav/sub-nav.html
  demo/style/base/_base.scss
  demo/style/demo/_demo-block.scss
  demo/style/demo/_demo-colors.scss
  demo/style/demo/_demo-grid.scss
  demo/style/lumapps.scss
  src/core/style/theme/lumapps/_variables.scss
Labels: need: dev-frontend

#50 docs(avatar)
  demo/angularjs/app.js
  demo/angularjs/components/avatar/demo.html
  demo/angularjs/components/avatar/doc.md
  demo/angularjs/components/avatar/partials/avatar.html
  demo/angularjs/layout/sub-nav/sub-nav.html
Labels: need: dev-frontend

#56 fix(thumbnail): correctly handle aspect ratio regarding size
  src/components/thumbnail/angularjs/thumbnail.html
  src/components/thumbnail/angularjs/thumbnail_directive.js
  src/components/thumbnail/react/Thumbnail.tsx
  src/components/thumbnail/style/lumapps/_index.scss
Labels: need: review-frontend

#53 Created the Popover component / feature to build advanced stuff
  demo/react/components/popover/controled.tsx
  demo/react/components/popover/default.tsx
  demo/react/components/popover/index.tsx
  demo/react/components/popover/matchParentWidth.tsx
  demo/react/components/popover/offsets.tsx
  demo/react/components/popover/placements.tsx
  demo/react/components/popover/realCase.tsx
  demo/react/components/popover/tooltip.tsx
  demo/react/layout/SubNav.tsx
  package.json
  src/components/popover/react/Popover.tsx
  src/components/popover/style/lumapps/_index.scss
  src/core/style/lumx-theme-lumapps.scss
  src/core/utils.js
  src/react.index.ts
  yarn.lock
Labels: need: dev-frontend

#55 Docs/review lm
  .gitignore
  demo/angularjs/components/button/doc.md
  demo/angularjs/components/checkbox/doc.md
  demo/angularjs/components/chip/doc.md
  demo/angularjs/components/dialog/doc.md
  demo/angularjs/components/dropdown/doc.md
  demo/angularjs/components/list/doc.md
  demo/angularjs/components/progress-tracker/doc.md
  demo/angularjs/components/radio-button/doc.md
  demo/angularjs/components/select/doc.md
  demo/angularjs/components/switch/doc.md
  demo/angularjs/components/table/doc.md
  demo/angularjs/components/text-field/doc.md
  demo/angularjs/components/toolbar/doc.md
  demo/angularjs/components/user-block/doc.md
Labels: need: review-doc

#59 docs(progress)
  demo/angularjs/app.js
  demo/angularjs/components/loading/demo.html
  demo/angularjs/components/loading/doc.md
  demo/angularjs/components/loading/partials/circular.html
  demo/angularjs/components/loading/partials/linear.html
  demo/angularjs/layout/sub-nav/sub-nav.html
Labels: need: review-doc

#42 fix(button): wrapped the children in a span
  src/components/button/react/Button.tsx
  src/components/button/react/__snapshots__/Button.test.tsx.snap
Labels: need: dev-frontend

#17 docs(image block)
  demo/angularjs/app.js
  demo/angularjs/components/image-block/controller.js
  demo/angularjs/components/image-block/demo.html
  demo/angularjs/components/image-block/doc.md
  demo/angularjs/components/image-block/partials/image-block-alignment.html
  demo/angularjs/components/image-block/partials/image-block-over.html
  demo/angularjs/components/image-block/partials/image-block-padding.html
  demo/angularjs/components/image-block/partials/image-block.html
Labels: need: dev-frontend

#57 Created List / listItem / listSubheader components
  demo/react/components/list/big.tsx
  demo/react/components/list/default.tsx
  demo/react/components/list/huge.tsx
  demo/react/components/list/index.tsx
  demo/react/components/list/tiny.tsx
  demo/react/index.html
  src/components/list-divider/react/ListDivider.tsx
  src/components/list-item/react/ListItem.tsx
  src/components/list-subheader/react/ListSubheader.tsx
  src/components/list/react/List.tsx
  src/core/constants.d.ts
  src/react.index.ts
Labels: need: dev-frontend

#64 feat(text-field): add component and demo
  demo/react/components/text-field/default.tsx
  demo/react/components/text-field/disabled.tsx
  demo/react/components/text-field/helperText.tsx
  demo/react/components/text-field/icon.tsx
  demo/react/components/text-field/index.tsx
  demo/react/components/text-field/invalid.tsx
  demo/react/components/text-field/placeholder.tsx
  demo/react/components/text-field/valid.tsx
  src/components/text-field/react/TextField.tsx
  src/core/utils.js
  src/react.index.ts
Labels: need: test

#74 fix(DropdownButton): fix
  src/components/button/react/DropdownButton.tsx
Labels: need: review-frontend

#67 feat(progress-tracker): add component and demo file
  demo/react/components/progress-tracker/default.tsx
  demo/react/components/progress-tracker/index.tsx
  src/components/progress-tracker/react/ProgressTracker.tsx
  src/components/progress-tracker/react/ProgressTrackerStep.tsx
  src/react.index.ts
Labels: need: test

#68 feat(chip): polish chip to new standards
  demo/react/components/chip/default.tsx
  src/components/chip/react/Chip.test.tsx
  src/components/chip/react/Chip.tsx
  src/components/chip/react/__snapshots__/Chip.test.tsx.snap
  src/components/image-block/react/ImageBlock.tsx
Labels: need: test

#71 Added item selection behavior (via click or navigation) + minor fixes on the list
  demo/react/components/list/tiny.tsx
  src/components/list-item/react/ListItem.tsx
  src/components/list/react/List.tsx
Labels: need: test
