Repository lumapps/design-system, pull requests merged in 2019-11, with the labels that each got.

#207 fix(switch): make Switch a controlled component
  CHANGELOG.react.md
  demo/react/components/switch/default.tsx
  demo/react/components/switch/index.tsx
  demo/react/components/switch/with-helpers.tsx
  demo/react/doc/product/components/switch.mdx
  demo/react/layout/DemoBlock.tsx
  src/components/switch/react/Switch.test.tsx
  src/components/switch/react/Switch.tsx
  src/components/switch/react/__snapshots__/Switch.test.tsx.snap
Labels: need: test

#212 chore(release): release v0.13.0 minor version for @lumx/react
  CHANGELOG.react.md
  src/core/react/package.json
Labels: need: review-frontend

#209 feat(autocomplete-multiple): react component
  CHANGELOG.react.md
  demo/react/doc/product/components/autocomplete.mdx
  src/components/autocomplete/react/Autocomplete.test.tsx
  src/components/autocomplete/react/Autocomplete.tsx
  src/components/autocomplete/react/AutocompleteMultiple.test.tsx
  src/components/autocomplete/react/AutocompleteMultiple.tsx
  src/components/autocomplete/react/__mockData__/index.js
  src/components/autocomplete/react/__snapshots__/Autocomplete.test.tsx.snap
  src/components/autocomplete/react/__snapshots__/AutocompleteMultiple.test.tsx.snap
  src/components/chip/react/Chip.tsx
  src/components/chip/react/ChipGroup.tsx
  src/components/chip/style/lumapps/_index.scss
  src/components/chip/style/lumapps/_mixins.scss
  src/components/dropdown/react/Dropdown.tsx
  src/core/constants.d.ts
  src/core/constants.js
  src/core/react/hooks/index.tsx
  src/core/react/hooks/useChipGroupNavigation.tsx
  src/core/react/hooks/useKeyboardListNavigation.tsx
  src/react.index.ts
Labels: need: review-doc, need: review-frontend, need: review-integration

#213 fix: incorrect rebase on CHANGELOG.react.md
  CHANGELOG.react.md
Labels: need: review-frontend

#215 feat(autocomplete-multi): change Chip deletion logic.
  CHANGELOG.react.md
  demo/react/doc/product/components/autocomplete.mdx
  src/components/autocomplete/react/Autocomplete.tsx
  src/components/chip/style/lumapps/_index.scss
  src/components/chip/style/lumapps/_mixins.scss
  src/components/popover/react/Popover.test.tsx
  src/components/popover/react/Popover.tsx
  src/components/popover/react/__snapshots__/Popover.test.tsx.snap
  src/components/select/react/Select.tsx
  src/core/react/hooks/index.tsx
  src/core/react/hooks/useFocusOnClose.tsx
Labels: need: review-integration, need: test

#218 chore(release): release @lumx/react v0.14.0
  CHANGELOG.react.md
  src/core/react/package.json
Labels: need: review-frontend

#208 feat(uploader): add component
  CHANGELOG.react.md
  demo/angularjs/app.js
  demo/angularjs/components/uploader/controller.js
  demo/angularjs/components/uploader/demo.html
  demo/angularjs/components/uploader/doc.md
  demo/angularjs/components/uploader/partials/circle.html
  demo/angularjs/components/uploader/partials/default.html
  demo/angularjs/layout/main-nav/main-nav_controller.js
  demo/react/components/slideshow/default.tsx
  demo/react/doc/product/components/image-block.mdx
  demo/react/doc/product/components/thumbnail.mdx
  demo/react/doc/product/components/uploader.mdx
  demo/react/layout/MainNav.tsx
  src/angularjs.index.js
  src/components/editable-media/react/EditableMedia.tsx
  src/components/image-block/react/ImageBlock.tsx
  src/components/index.ts
  src/components/post-block/react/PostBlock.tsx
  src/components/thumbnail/react/Thumbnail.tsx
  src/components/uploader/angularjs/uploader.html
  src/components/uploader/angularjs/uploader_directive.js
  src/components/uploader/react/Uploader.test.tsx
  src/components/uploader/react/Uploader.tsx
  src/components/uploader/react/__snapshots__/Uploader.test.tsx.snap
  src/components/uploader/style/lumapps/_index.scss
  src/core/angularjs/lumx.js
  src/core/style/lumx-theme-lumapps.scss
  src/react.index.ts
Labels: need: test

#221 chore(release): release new minor version 0.15.0 for @lumx/react
  CHANGELOG.react.md
  src/core/react/package.json
Labels: need: review-frontend

#217 fix(lightbox): fix body scrollbar flickering when children updates
  CHANGELOG.react.md
  demo/react/doc/product/components/lightbox.mdx
  src/components/dialog/style/lumapps/_index.scss
  src/components/lightbox/react/Lightbox.tsx
Labels: need: test

#198 feat(demo): static website build
  demo/react/App.tsx
  demo/react/doc/partners/site-templates.mdx
  demo/react/doc/product/components/date-picker.mdx
  demo/react/index.html
  demo/react/index.html.ejs
  demo/react/layout/MainContent.tsx
  demo/react/layout/MainNav.tsx
  demo/style/lumapps.scss
  demo/style/material.scss
  package.json
  src/core/react/utils.ts
  webpack/react/webpack.config.js
  webpack/react/webpack.demo-site.js
  webpack/react/webpack.dev.js
  webpack/webpack.config.js
  yarn.lock
Labels: in progress

#230 fix: ie11 compatibility
  demo/angularjs/components/list/partials/big.html
  demo/angularjs/components/list/partials/huge.html
  demo/angularjs/components/list/partials/regular.html
  demo/angularjs/index.html
  demo/style/demo/_demo-block.scss
  demo/style/layout/_asset-block.scss
  demo/style/layout/main/_main.scss
  package.json
  src/components/button/style/lumapps/_mixins.scss
  src/components/chip/style/lumapps/_mixins.scss
  src/components/comment-block/style/lumapps/_index.scss
  src/components/dialog/angularjs/dialog_directive.js
  src/components/dialog/style/lumapps/_index.scss
  src/components/expansion-panel/style/lumapps/_index.scss
  src/components/grid/style/lumapps/_index.scss
  src/components/image-block/style/lumapps/_index.scss
  src/components/list/style/lumapps/_mixins.scss
  src/components/post-block/style/lumapps/_index.scss
  src/components/progress-tracker/style/lumapps/_index.scss
  src/components/select/style/lumapps/_index.scss
  src/components/side-navigation/style/lumapps/_index.scss
  src/components/side-navigation/style/lumapps/_mixins.scss
  src/components/slider/style/lumapps/_index.scss
  src/components/slideshow/style/lumapps/_index.scss
  src/components/switch/style/lumapps/_index.scss
  src/components/tabs/style/lumapps/_mixins.scss
  src/components/text-field/style/lumapps/_index.scss
  src/components/text-field/style/lumapps/_mixins.scss
  src/components/thumbnail/style/lumapps/_index.scss
  yarn.lock
Labels: need: dev-frontend

#233 fix(slideshow-controls): put a setState func in a useEffect
  src/components/slideshow/react/SlideshowControls.tsx
Labels: need: review-frontend

#228 fix(tooltip): use Popover for tooltip component
  CHANGELOG.react.md
  src/components/tooltip/react/Tooltip.tsx
  src/components/tooltip/react/__snapshots__/Tooltip.test.tsx.snap
  src/components/tooltip/style/lumapps/_index.scss
  src/core/react/package.json
Labels: need: rebase, need: test

#235 chore(release): release v0.17.0
  CHANGELOG.react.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#236 fix(demo): fix break line in MDX paragraph
  packages/site-demo/webpack-loader/mdx-loader/mdx-break-line.js
Labels: need: review-frontend

#237 feat(storybook): added storybook 💅🏻
  README.md
  package.json
  packages/lumx-react/.storybook/config.js
  packages/lumx-react/.storybook/webpack.config.js
  packages/lumx-react/package.json
  packages/lumx-react/src/components/avatar/Avatar.stories.tsx
  yarn.lock
Labels: need: review-doc, need: review-frontend

#240 fix(demo): correctly show error on missing react demo
  packages/site-demo/src/layout/DemoBlock.tsx
Labels: need: test

#242 fix(demo): fix console error on break line in MDX
  packages/site-demo/webpack-loader/mdx-loader/index.js
  packages/site-demo/webpack-loader/mdx-loader/mdx-break-line.js
Labels: need: review-frontend, need: test

#246 Chore: optimize demo bundle size
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-react/package.json
  packages/site-demo/src/index.html.ejs
  packages/site-demo/webpack.config.js
Labels: need: review-frontend

#239 feat(addons): Added several storybook addons
  packages/lumx-react/.storybook/addons.js
  packages/lumx-react/.storybook/webpack.config.js
  packages/lumx-react/package.json
  packages/lumx-react/src/components/avatar/Avatar.stories.tsx
  packages/lumx-react/src/components/button/Button.stories.tsx
  packages/lumx-react/src/story-block/StoryBlock.jsx
  packages/lumx-react/src/story-block/decorators.js
  packages/lumx-react/src/story-block/index.jsx
  packages/lumx-react/src/story-block/styles.js
  yarn.lock
Labels: need: merge, need: rebase

#245 chore(demo): replace highlight.js with prism
  packages/site-demo/package.json
  packages/site-demo/src/index.tsx
  packages/site-demo/src/layout/DemoBlock.tsx
  packages/site-demo/src/layout/utils/useHighlightedCode.ts
  packages/site-demo/src/style/demo/_demo-block.scss
  packages/site-demo/webpack.config.js
  yarn.lock
Labels: need: rebase

#247 Release v0.18.0
  CHANGELOG.react.md
  lerna.json
  package.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend
