Repository lumapps/design-system, pull requests merged in 2019-08, with the labels that each got.

#120 Feat/text field value
  demo/angularjs/components/text-field/partials/default.html
  demo/angularjs/components/text-field/partials/disabled.html
  demo/angularjs/components/text-field/partials/error.html
  demo/angularjs/components/text-field/partials/helper.html
  demo/angularjs/components/text-field/partials/placeholder.html
  demo/angularjs/components/text-field/partials/valid.html
  demo/react/components/text-field/default.tsx
  demo/react/components/text-field/disabled.tsx
  demo/react/components/text-field/helperText.tsx
  demo/react/components/text-field/icon.tsx
  demo/react/components/text-field/invalid.tsx
  demo/react/components/text-field/placeholder.tsx
  demo/react/components/text-field/valid.tsx
  demo/react/components/toolbar/default.tsx
  src/components/text-field/react/TextField.test.tsx
  src/components/text-field/react/TextField.tsx
  src/components/text-field/react/__snapshots__/TextField.test.tsx.snap
Labels: need: test

#117 feat(grid): use css classes instead of attributes
  demo/react/components/grid/default.tsx
  demo/react/components/grid/vertical.tsx
  src/components/grid/react/Grid.tsx
  src/components/grid/react/GridItem.tsx
  src/components/index.ts
Labels: need: test

#115 feat(editable-media): add component
  demo/angularjs/app.js
  demo/angularjs/components/editable-media/controller.js
  demo/angularjs/components/editable-media/demo.html
  demo/angularjs/layout/sub-nav/sub-nav.html
  src/angularjs.index.js
  src/components/avatar/style/lumapps/_index.scss
  src/components/editable-media/angularjs/editable-media.html
  src/components/editable-media/angularjs/editable-media_directive.js
  src/components/editable-media/style/lumapps/_index.scss
  src/components/thumbnail/style/lumapps/_index.scss
  src/core/angularjs/lumx.js
  src/core/style/lumx-theme-lumapps.scss
  src/core/style/size/lumapps/_variables.scss
Labels: need: dev-frontend

#122 feat(side-navigation): add react component
  demo/react/components/side-navigation/default.tsx
  demo/react/components/side-navigation/index.tsx
  demo/react/layout/SubNav.tsx
  src/components/button/react/Button.tsx
  src/components/expansion-panel/react/ExpansionPanel.tsx
  src/components/index.ts
  src/components/side-navigation/react/SideNavigation.test.tsx
  src/components/side-navigation/react/SideNavigation.tsx
  src/components/side-navigation/react/SideNavigationItem.test.tsx
  src/components/side-navigation/react/SideNavigationItem.tsx
  src/components/side-navigation/react/__snapshots__/SideNavigation.test.tsx.snap
  src/components/side-navigation/react/__snapshots__/SideNavigationItem.test.tsx.snap
  src/core/react/utils.ts
  src/core/utils.js
  src/react.index.ts
Labels: need: merge

#110 feat(demo): new demo layout
  demo/angularjs/app.js
  demo/angularjs/components/avatar/doc.md
  demo/angularjs/components/avatar/partials/parameters.html
  demo/angularjs/components/side-navigation/demo.html
  demo/angularjs/foundations/colors/controller.js
  demo/angularjs/index.html
  demo/angularjs/layout/main-nav/main-nav.html
  demo/angularjs/layout/main-nav/main-nav_controller.js
  demo/angularjs/layout/main/main-header.html
  demo/angularjs/layout/main/main-header_directive.js
  demo/angularjs/layout/sub-nav/sub-nav.html
  demo/angularjs/layout/sub-nav/sub-nav_controller.js
  demo/assets/images/logo.svg
  demo/constants.d.ts
  demo/constants.js
  demo/react/App.tsx
  demo/react/doc/main.mdx
  demo/react/doc/product/components/chip.mdx
  demo/react/doc/product/components/expansion-panel.mdx
  demo/react/doc/product/components/side-navigation.mdx
  demo/react/doc/product/foundations/colors.mdx
  demo/react/doc/product/foundations/typography.mdx
  demo/react/index.css
  demo/react/index.html
  demo/react/index.tsx
  demo/react/layout/DemoBlock.tsx
  demo/react/layout/DemoColor.tsx
  demo/react/layout/DemoHeader.tsx
  demo/react/layout/ErrorBoundary.tsx
  demo/react/layout/Main.tsx
  demo/react/layout/MainContent.tsx
  demo/react/layout/MainNav.tsx
  demo/react/layout/PropTable.tsx
  demo/react/layout/SubNav.tsx
  demo/react/layout/SubNavItem.tsx
  demo/react/layout/ThemeSelector.tsx
  demo/style/layout/main-nav/_main-nav.scss
  demo/style/layout/main/_main.scss
  demo/style/layout/sub-nav/_sub-nav.scss
  demo/style/lumapps.scss
  jest/react/index.js
  package.json
  src/components/button/react/Button.tsx
  src/components/side-navigation/angularjs/side-navigation-item.html
  src/components/side-navigation/angularjs/side-navigation-item_directive.js
  src/components/side-navigation/style/lumapps/_index.scss
  webpack/.eslintrc.js
  webpack/react/mdx-demo-code-extractor/index.js
  webpack/react/props-loader/convertPropTable.js
  webpack/react/props-loader/convertPropTable.spec.js
  webpack/react/props-loader/index.js
  webpack/react/webpack.config.js
  webpack/utils.js
  webpack/webpack.config.js
  yarn.lock
Labels: need: merge

#116 feat(icon): add color variant parameter
  src/components/icon/angularjs/icon_directive.js
  src/components/icon/react/Icon.test.tsx
  src/components/icon/react/Icon.tsx
  src/components/icon/react/__snapshots__/Icon.test.tsx.snap
  src/components/icon/style/lumapps/_index.scss
  src/components/icon/style/lumapps/_mixins.scss
  src/components/index.ts
Labels: need: merge

#118 feat(react-popover): rework popover component to remove popperjs
  demo/react/components/dropdown/default.tsx
  demo/react/components/dropdown/target.tsx
  demo/react/components/popover/controled.tsx
  demo/react/components/popover/default.tsx
  demo/react/components/popover/index.tsx
  demo/react/components/popover/matchParentWidth.tsx
  demo/react/components/popover/offsets.tsx
  demo/react/components/popover/placements.tsx
  demo/react/components/popover/realCase.tsx
  demo/react/components/popover/tooltip.tsx
  demo/react/doc/product/components/popover.mdx
  demo/react/layout/ElementWithRef.tsx
  src/components/button/react/DropdownButton.test.tsx
  src/components/button/react/__snapshots__/DropdownButton.test.tsx.snap
  src/components/dropdown/react/Dropdown.test.tsx
  src/components/dropdown/react/Dropdown.tsx
  src/components/dropdown/react/__snapshots__/Dropdown.test.tsx.snap
  src/components/popover/react/Popover.test.tsx
  src/components/popover/react/Popover.tsx
  src/components/popover/react/__snapshots__/Popover.test.tsx.snap
  src/components/user-block/react/UserBlock.tsx
  src/core/react/hooks/index.tsx
  src/core/react/hooks/useComputePosition.tsx
  src/core/react/utils/calculatePopoverPlacement.ts
  src/core/react/utils/index.tsx
  src/core/react/utils/isInViewPort.ts
  src/core/utils.d.ts
  src/react.index.ts
  webpack/react/mdx-demo-code-extractor/index.js
Labels: need: review-integration

#119 feat(dropdown): react component
  demo/react/components/dropdown/default.tsx
  demo/react/components/dropdown/target.tsx
  demo/react/components/popover/default.tsx
  demo/react/components/popover/matchParentWidth.tsx
  demo/react/doc/product/components/dropdown.mdx
  src/components/button/react/ButtonGroup.tsx
  src/components/button/react/DropdownButton.tsx
  src/components/button/react/__snapshots__/DropdownButton.test.tsx.snap
  src/components/dropdown/angularjs/dropdown_directive.js
  src/components/dropdown/react/Dropdown.test.tsx
  src/components/dropdown/react/Dropdown.tsx
  src/components/dropdown/react/__snapshots__/Dropdown.test.tsx.snap
  src/components/dropdown/style/lumapps/_index.scss
  src/components/popover/react/Popover.test.tsx
  src/components/popover/react/Popover.tsx
  src/components/popover/react/__snapshots__/Popover.test.tsx.snap
  src/components/tooltip/react/Tooltip.tsx
  src/core/react/hooks/useClickAway.tsx
  src/core/react/hooks/useComputePosition.tsx
  src/global.d.ts
Labels: need: dev-integration

#90 feat(select): react component
  demo/react/components/popover/realCase.tsx
  demo/react/components/select/chipSelection.tsx
  demo/react/components/select/constants.ts
  demo/react/components/select/default.tsx
  demo/react/components/select/index.tsx
  demo/react/components/select/multiSelection.tsx
  demo/react/components/select/multiSelectionWithSearch.tsx
  demo/react/components/select/mutiChipSelection.tsx
  demo/react/components/select/selectInvalid.tsx
  demo/react/components/select/selectValid.tsx
  demo/react/doc/product/components/popover.mdx
  demo/react/doc/product/components/select.mdx
  src/components/chip/react/Chip.tsx
  src/components/dropdown/react/Dropdown.tsx
  src/components/list/react/List.tsx
  src/components/select/react/Select.test.tsx
  src/components/select/react/Select.tsx
  src/components/select/react/__snapshots__/Select.test.tsx.snap
  src/components/select/style/lumapps/_mixins.scss
  src/core/constants.d.ts
  src/core/constants.js
  src/core/react/hooks/index.tsx
  src/core/react/hooks/useBooleanState.tsx
  src/core/react/hooks/useInfiniteScroll.tsx
  src/core/react/utils.ts
  src/react.index.ts
Labels: need: test
