Repository lumapps/design-system, pull requests merged in 2019-12, with the labels that each got.

#251 fix(demo): fix error on missing angularjs demo
  packages/site-demo/src/layout/DemoBlock.tsx
Labels: need: review-frontend

#267 fix(demo): fix switch engine on PropTable
  packages/site-demo/src/layout/PropTable.tsx
  packages/site-demo/webpack-loader/mdx-loader/mdx-demo-code-extractor.js
Labels: need: review-frontend

#258 docs(iconography)(new): page content
  packages/site-demo/content/product/foundations/iconography/assets/iconography-keylines.png
  packages/site-demo/content/product/foundations/iconography/assets/iconography-layout.png
  packages/site-demo/content/product/foundations/iconography/index.mdx
  packages/site-demo/content/product/foundations/iconography/react/default.tsx
  packages/site-demo/content/product/foundations/iconography/react/layout.tsx
  packages/site-demo/src/layout/MainNav.tsx
Labels: need: review-doc

#262 docs(toolbar): page content
  packages/site-demo/content/product/components/toolbar/assets/anatomy.png
  packages/site-demo/content/product/components/toolbar/index.mdx
  packages/site-demo/content/product/components/toolbar/react/back.tsx
  packages/site-demo/content/product/components/toolbar/react/default.tsx
  packages/site-demo/content/product/components/toolbar/react/dialog.tsx
  packages/site-demo/content/product/components/toolbar/react/media-picker.tsx
Labels: need: review-doc

#203 feat(text-field): add maxlength prop for react
  CHANGELOG.react.md
  packages/lumx-angularjs/src/components/select/select.html
  packages/lumx-angularjs/src/components/text-field/text-field.html
  packages/lumx-angularjs/src/components/text-field/text-field_directive.js
  packages/lumx-core/src/scss/components/select/lumapps/_index.scss
  packages/lumx-core/src/scss/components/select/material/_index.scss
  packages/lumx-core/src/scss/components/text-field/lumapps/_index.scss
  packages/lumx-core/src/scss/components/text-field/lumapps/_mixins.scss
  packages/lumx-core/src/scss/components/text-field/material/_index.scss
  packages/lumx-core/src/scss/components/text-field/material/_mixins.scss
  packages/lumx-react/src/components/select/Select.tsx
  packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
  packages/lumx-react/src/components/text-field/TextField.tsx
  packages/lumx-react/src/components/text-field/__snapshots__/TextField.test.tsx.snap
  packages/site-demo/content/product/components/text-field/angularjs/character-counter.html
  packages/site-demo/content/product/components/text-field/angularjs/helper.html
  packages/site-demo/content/product/components/text-field/index.mdx
  packages/site-demo/content/product/components/text-field/react/character-counter.tsx
  packages/site-demo/content/product/components/text-field/react/clearable.tsx
Labels: need: test

#187 docs(slideshow): doc text update
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/site-demo/content/product/components/date-picker/index.mdx
  packages/site-demo/content/product/components/slideshow/index.mdx
  packages/site-demo/content/product/components/slideshow/react/auto.tsx
  packages/site-demo/content/product/components/slideshow/react/default.tsx
  packages/site-demo/content/product/components/slideshow/react/group.tsx
Labels: need: dev-frontend

#271 fix(demo): fix hot code reloading of SCSS/CSS styles
  packages/site-demo/package.json
  packages/site-demo/src/context/theme.tsx
  packages/site-demo/src/index.html.ejs
  packages/site-demo/src/theme-switch/index.ts
  packages/site-demo/src/theme-switch/switch-dev.ts
  packages/site-demo/src/theme-switch/switch-prod.ts
  packages/site-demo/webpack.config.js
  yarn.lock
Labels: need: review-frontend

#273 fix(demo): prevent loading of both material and lumapps theme
  packages/site-demo/src/context/theme.tsx
Labels: need: review-frontend

#248 feat(autocomplete): stories and fixes
  CHANGELOG.react.md
  packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx
  packages/lumx-react/src/components/autocomplete/Autocomplete.tsx
  packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx
  packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.tsx
  packages/lumx-react/src/hooks/useComputePosition.tsx
  packages/lumx-react/src/hooks/useFocusOnClose.tsx
  packages/lumx-react/src/hooks/useKeyboardListNavigation.tsx
  packages/site-demo/content/product/components/autocomplete/react/multiple.tsx
Labels: need: merge

#249 feat(date-picker)
  packages/lumx-core/package.json
  packages/lumx-core/src/js/date-picker.d.ts
  packages/lumx-core/src/js/date-picker.js
  packages/lumx-core/src/scss/components/date-picker/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-react/.storybook/webpack.config.js
  packages/lumx-react/src/components/date-picker/DatePicker.stories.tsx
  packages/lumx-react/src/components/date-picker/DatePicker.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.tsx
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/lumx-react/src/index.ts
  packages/site-demo/content/product/components/select/index.mdx
  yarn.lock
Labels: need: test

#274 fix(demo): bring back demo grid lost during the great refactoring
  packages/site-demo/content/product/components/grid/index.mdx
  packages/site-demo/src/layout/MainNav.tsx
Labels: need: test

#263 docs(uploader): page content
  packages/site-demo/content/product/components/uploader/angularjs/avatar.html
  packages/site-demo/content/product/components/uploader/angularjs/circle.html
  packages/site-demo/content/product/components/uploader/angularjs/controller.js
  packages/site-demo/content/product/components/uploader/angularjs/default.html
  packages/site-demo/content/product/components/uploader/angularjs/thumbnail.html
  packages/site-demo/content/product/components/uploader/index.mdx
  packages/site-demo/content/product/components/uploader/react/avatar.tsx
  packages/site-demo/content/product/components/uploader/react/default.tsx
  packages/site-demo/content/product/components/uploader/react/thumbnail.tsx
Labels: need: review-doc

#278 feat(expansion-panel): replace variant by hasBackground prop
  CHANGELOG.react.md
  packages/lumx-angularjs/src/components/expansion-panel/expansion-panel_directive.js
  packages/lumx-core/src/scss/components/expansion-panel/lumapps/_index.scss
  packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx
  packages/lumx-react/src/components/expansion-panel/__snapshots__/ExpansionPanel.test.tsx.snap
  packages/lumx-react/src/index.ts
  packages/site-demo/content/product/components/expansion-panel/angularjs/default.html
  packages/site-demo/content/product/components/expansion-panel/angularjs/drag-handle.html
  packages/site-demo/content/product/components/expansion-panel/angularjs/examples.html
  packages/site-demo/content/product/components/expansion-panel/angularjs/trimmed.html
  packages/site-demo/content/product/components/expansion-panel/react/default.tsx
  packages/site-demo/content/product/components/expansion-panel/react/drag-handle.tsx
  packages/site-demo/content/product/components/expansion-panel/react/examples.tsx
  packages/site-demo/content/product/components/expansion-panel/react/trimmed.tsx
Labels: need: test

#280 fix(date-picker): remove hook in loop
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
Labels: need: test

#282 feat(icon): add has shape attribute
  CHANGELOG.react.md
  packages/lumx-angularjs/src/components/icon/icon_directive.js
  packages/lumx-core/src/scss/_components-lumapps.scss
  packages/lumx-core/src/scss/components/icon/lumapps/_index.scss
  packages/lumx-core/src/scss/components/icon/lumapps/_mixins.scss
  packages/lumx-core/src/scss/components/icon/lumapps/_variables.scss
  packages/lumx-react/src/components/icon/Icon.stories.tsx
  packages/lumx-react/src/components/icon/Icon.tsx
  packages/lumx-react/src/components/icon/__snapshots__/Icon.test.tsx.snap
  packages/lumx-react/src/index.ts
  packages/lumx-react/src/story-block/StoryBlock.jsx
Labels: need: review-frontend, need: test

#284 feat(list): add item padding prop
  CHANGELOG.react.md
  packages/lumx-angularjs/src/components/list/list-item_directive.js
  packages/lumx-angularjs/src/components/list/list_directive.js
  packages/lumx-core/src/scss/components/list/lumapps/_index.scss
  packages/lumx-core/src/scss/components/list/lumapps/_mixins.scss
  packages/lumx-core/src/scss/components/list/lumapps/_variables.scss
  packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx
  packages/lumx-react/src/components/autocomplete/Autocomplete.test.tsx
  packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.test.tsx
  packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/lumx-react/src/components/autocomplete/__snapshots__/AutocompleteMultiple.test.tsx.snap
  packages/lumx-react/src/components/list/List.tsx
  packages/lumx-react/src/components/list/ListItem.tsx
  packages/lumx-react/src/index.ts
  packages/lumx-react/src/utils/type.ts
  packages/site-demo/content/product/components/autocomplete/react/default.tsx
  packages/site-demo/content/product/components/autocomplete/react/multiple.tsx
  packages/site-demo/content/product/components/list/react/regular.tsx
  packages/site-demo/content/product/components/select/react/multi-select-chip.tsx
  packages/site-demo/content/product/components/select/react/multi-select-search.tsx
Labels: need: review-frontend, need: test

#283 fix(color palettes): updated yellows for both themes
  packages/lumx-core/src/scss/core/theme/lumapps/_color-palette.scss
  packages/lumx-core/src/scss/core/theme/material/_color-palette.scss
Labels: need: dev-integration, need: test

#285 feat(badge): add badge in React and associated test
  packages/lumx-react/src/components/badge/Badge.stories.tsx
  packages/lumx-react/src/components/badge/Badge.test.tsx
  packages/lumx-react/src/components/badge/Badge.tsx
  packages/lumx-react/src/components/badge/__snapshots__/Badge.test.tsx.snap
  packages/lumx-react/src/index.ts
Labels: need: review-frontend
