Repository lumapps/design-system, pull requests merged in 2019-04, with the labels that each got.

#11 docs(progress-tracker)
  demo/angularjs/components/progress-tracker/controller.js
  demo/angularjs/components/progress-tracker/demo.html
  demo/angularjs/components/progress-tracker/partials/completed.html
  demo/angularjs/components/progress-tracker/partials/current.html
  demo/angularjs/components/progress-tracker/partials/error.html
  demo/angularjs/components/progress-tracker/partials/future.html
  demo/angularjs/components/progress-tracker/partials/helper.html
  demo/angularjs/components/progress-tracker/partials/stepper.html
  demo/angularjs/layout/main/main-block.html
  demo/angularjs/layout/main/main-block_directive.js
  src/components/progress-tracker/angularjs/progress-tracker-step_directive.js
  src/components/progress-tracker/style/lumapps/_index.scss
Labels: need: review-doc

#23 feat(divider): use variable for color variant
  src/components/data-table/style/lumapps/_index.scss
  src/components/dialog/style/lumapps/_index.scss
  src/components/divider/style/lumapps/_mixins.scss
  src/components/divider/style/lumapps/_variables.scss
  src/components/list/style/lumapps/_mixins.scss
  src/components/progress-tracker/style/lumapps/_index.scss
  src/components/select/style/lumapps/_mixins.scss
  src/components/tabs/style/lumapps/_mixins.scss
  src/components/text-field/style/material/_mixins.scss
  src/core/style/_components-lumapps.scss
Labels: need: review-integration

#22 docs(select)
  demo/angularjs/components/select/demo.html
  demo/angularjs/components/select/partials/multi-select-search.html
  demo/angularjs/components/select/partials/multi-select.html
  demo/angularjs/components/select/partials/single-select.html
  demo/angularjs/components/select/partials/validation-invalid.html
  demo/angularjs/components/select/partials/validation-valid.html
Labels: need: review-doc

#25 chore(demo): properly disable scroll on dropdown or dialog open
  demo/angularjs/app.js
  demo/style/layout/main/_main.scss
  demo/style/layout/sub-nav/_sub-nav.scss
Labels: need: test

#28 Feat/slideshow
  demo/angularjs/app.js
  demo/angularjs/components/slideshow/controller.js
  demo/angularjs/components/slideshow/demo.html
  demo/angularjs/layout/sub-nav/sub-nav.html
  src/angularjs.index.js
  src/components/slideshow/angularjs/slideshow-controls.html
  src/components/slideshow/angularjs/slideshow-controls_directive.js
  src/components/slideshow/angularjs/slideshow-item.html
  src/components/slideshow/angularjs/slideshow-item_directive.js
  src/components/slideshow/angularjs/slideshow.html
  src/components/slideshow/angularjs/slideshow_directive.js
  src/components/slideshow/style/lumapps/_index.scss
  src/components/slideshow/style/lumapps/_variables.scss
  src/core/angularjs/lumx.js
  src/core/style/_components-lumapps.scss
  src/core/style/lumx-theme-lumapps.scss
Labels: need: review-frontend

#29 Feat/lightbox
  demo/angularjs/app.js
  demo/angularjs/components/lightbox/controller.js
  demo/angularjs/components/lightbox/demo.html
  demo/angularjs/layout/sub-nav/sub-nav.html
  src/angularjs.index.js
  src/components/dialog/angularjs/dialog_directive.js
  src/components/dialog/style/lumapps/_index.scss
  src/components/lightbox/angularjs/lightbox.html
  src/components/lightbox/angularjs/lightbox_directive.js
  src/components/lightbox/angularjs/lightbox_service.js
  src/components/lightbox/style/lumapps/_index.scss
  src/components/lightbox/style/lumapps/_variables.scss
  src/core/angularjs/lumx.js
  src/core/style/_components-lumapps.scss
  src/core/style/lumx-theme-lumapps.scss
Labels: need: review-frontend

#32 feat(user-block)
  demo/angularjs/app.js
  demo/angularjs/components/user-block/controller.js
  demo/angularjs/components/user-block/demo.html
  demo/angularjs/layout/sub-nav/sub-nav.html
  src/angularjs.index.js
  src/components/tabs/style/lumapps/_mixins.scss
  src/components/thumbnail/angularjs/thumbnail_directive.js
  src/components/thumbnail/style/lumapps/_index.scss
  src/components/user-block/angularjs/user-block.html
  src/components/user-block/angularjs/user-block_directive.js
  src/components/user-block/style/lumapps/_index.scss
  src/core/angularjs/lumx.js
  src/core/style/_core-lumapps.scss
  src/core/style/grid/lumapps/_index.scss
  src/core/style/link/lumapps/_mixins.scss
  src/core/style/lumx-theme-lumapps.scss
  src/core/style/size/lumapps/_variables.scss
Labels: need: review-frontend

#34 feat(table): revamp the table component
  demo/angularjs/app.js
  demo/angularjs/components/data-table/controller.js
  demo/angularjs/components/data-table/demo.html
  demo/angularjs/components/data-table/partials/avatar-layout.html
  demo/angularjs/components/data-table/partials/default.html
  demo/angularjs/components/table/controller.js
  demo/angularjs/components/table/demo.html
  demo/angularjs/components/table/partials/default.html
  demo/angularjs/layout/sub-nav/sub-nav.html
  src/angularjs.index.js
  src/components/data-table/angularjs/data-table.html
  src/components/data-table/angularjs/data-table_directive.js
  src/components/data-table/angularjs/data-table_service.js
  src/components/data-table/style/lumapps/_index.scss
  src/components/table/angularjs/table-body_directive.js
  src/components/table/angularjs/table-cell.html
  src/components/table/angularjs/table-cell_directive.js
  src/components/table/angularjs/table-head_directive.js
  src/components/table/angularjs/table-row.html
  src/components/table/angularjs/table-row_directive.js
  src/components/table/angularjs/table_directive.js
  src/components/table/style/lumapps/_index.scss
  src/core/angularjs/lumx.js
  src/core/style/lumx-theme-lumapps.scss
Labels: need: review-frontend

#35 feat(thumbnail): created a React version of the thumbnail component
  demo/react/components/thumbnail/default.tsx
  demo/react/components/thumbnail/index.tsx
  demo/react/components/thumbnail/rounded.tsx
  demo/react/layout/SubNav.tsx
  src/components/thumbnail/react/Thumbnail.tsx
  src/react.index.ts
Labels: need: test

#26 docs(switch)
  demo/angularjs/components/switch/demo.html
  demo/angularjs/components/switch/partials/default.html
Labels: need: test

#27 docs(toolbar)
  demo/angularjs/components/toolbar/controller.js
  demo/angularjs/components/toolbar/demo.html
  demo/angularjs/components/toolbar/partials/back.html
  demo/angularjs/components/toolbar/partials/default.html
  demo/angularjs/components/toolbar/partials/dialog.html
  demo/angularjs/components/toolbar/partials/media-picker.html
Labels: need: dev-frontend, need: test

#24 docs(textfield)
  demo/angularjs/components/text-field/controller.js
  demo/angularjs/components/text-field/demo.html
  demo/angularjs/components/text-field/partials/default.html
  demo/angularjs/components/text-field/partials/disabled.html
  demo/angularjs/components/text-field/partials/error.html
  demo/angularjs/components/text-field/partials/helper.html
  demo/angularjs/components/text-field/partials/icon.html
  demo/angularjs/components/text-field/partials/placeholder.html
  demo/angularjs/components/text-field/partials/valid.html
Labels: need: dev-frontend, need: test

#36 fix(util): always use kebab-case for basic computed css properties
  src/core/utils.js
Labels: need: review-frontend

#31 docs(list)
  demo/angularjs/components/dropdown/partials/default.html
  demo/angularjs/components/dropdown/partials/target.html
  demo/angularjs/components/expansion-panel/demo.html
  demo/angularjs/components/list/controller.js
  demo/angularjs/components/list/demo.html
  demo/angularjs/components/list/partials/big.html
  demo/angularjs/components/list/partials/huge.html
  demo/angularjs/components/list/partials/regular.html
  demo/angularjs/components/list/partials/tiny.html
  demo/style/layout/sub-nav/_sub-nav.scss
  src/components/list/angularjs/list-item.html
  src/components/list/angularjs/list-item_directive.js
  src/components/list/style/lumapps/_index.scss
  src/components/list/style/lumapps/_mixins.scss
  src/components/list/style/lumapps/_variables.scss
  src/components/select/angularjs/select.html
  src/components/select/style/lumapps/_mixins.scss
Labels: need: review-doc

#41 feat(chip): create chip component
  demo/react/components/chip/default.tsx
  demo/react/components/chip/index.tsx
  src/components/chip/react/Chip.test.tsx
  src/components/chip/react/Chip.tsx
  src/components/chip/react/__snapshots__/Chip.test.tsx.snap
  src/react.index.ts
Labels: need: review-frontend

#40 feat(userblock): created userblock component
  demo/react/components/user-block/default.tsx
  demo/react/components/user-block/horizontal.tsx
  demo/react/components/user-block/index.tsx
  demo/react/layout/SubNav.tsx
  src/components/index.ts
  src/components/user-block/react/UserBlock.tsx
  src/react.index.ts
Labels: need: test

#39 docs(user-block)
  demo/angularjs/components/user-block/demo.html
  demo/angularjs/components/user-block/doc.md
  demo/angularjs/components/user-block/partials/extended.html
  demo/angularjs/components/user-block/partials/size-l.html
  demo/angularjs/components/user-block/partials/size-m.html
  demo/angularjs/components/user-block/partials/size-s.html
  demo/angularjs/components/user-block/partials/vertical.html
Labels: need: review-frontend

#49 Feat/advanced thumbnail
  demo/angularjs/components/list/partials/big.html
  demo/angularjs/components/list/partials/huge.html
  demo/angularjs/components/list/partials/regular.html
  demo/react/components/thumbnail/default.tsx
  demo/react/components/thumbnail/rounded.tsx
  src/angularjs.index.js
  src/components/avatar/angularjs/avatar_directive.js
  src/components/avatar/style/lumapps/_index.scss
  src/components/image-block/angularjs/image-block.html
  src/components/image-block/angularjs/image-block_directive.js
  src/components/image-block/style/lumapps/_index.scss
  src/components/thumbnail/angularjs/thumbnail.html
  src/components/thumbnail/angularjs/thumbnail_directive.js
  src/components/thumbnail/react/Thumbnail.tsx
  src/components/thumbnail/style/lumapps/_index.scss
  src/components/thumbnail/style/lumapps/_variables.scss
  src/components/user-block/angularjs/user-block.html
  src/components/user-block/react/UserBlock.tsx
  src/core/angularjs/lumx.js
  src/core/style/_components-lumapps.scss
  src/core/style/lumx-theme-lumapps.scss
  src/react.index.ts
Labels: need: test

#37 feat(image-block): create imageblock skeleton
  demo/react/components/image-block/default.tsx
  demo/react/components/image-block/index.tsx
  src/components/image-block/react/ImageBlock.tsx
  src/components/thumbnail/react/Thumbnail.tsx
  src/react.index.ts
Labels: need: test

#46 Feat/slideshow LUM-2537
  demo/react/components/slideshow/default.tsx
  demo/react/components/slideshow/index.tsx
  demo/react/layout/SubNav.tsx
  src/components/button/react/DropdownButton.tsx
  src/components/slideshow/angularjs/slideshow-controls_directive.js
  src/components/slideshow/angularjs/slideshow_directive.js
  src/components/slideshow/constants.ts
  src/components/slideshow/react/Slideshow.tsx
  src/components/slideshow/react/SlideshowControls.tsx
  src/components/slideshow/react/SlideshowItem.tsx
  src/components/slideshow/style/lumapps/_index.scss
  src/core/utils.d.ts
  src/core/utils.js
  src/react.index.ts
Labels: in progress
