Repository lumapps/design-system, pull requests merged in 2019-10, with the labels that each got.

#164 refactor(slider): make it fully controlled and remove old demo
  demo/react/components/slider/default.tsx
  demo/react/components/slider/index.tsx
  demo/react/components/slider/nolabel.tsx
  demo/react/components/slider/precision.tsx
  demo/react/components/slider/style.css
  demo/react/components/slider/withsteps.tsx
  demo/react/doc/product/components/slider.mdx
  src/components/slider/react/Slider.tsx
Labels: need: test

#170 Feat/editable media
  CHANGELOG.react.md
  demo/react/components/editable-media/default.tsx
  demo/react/doc/product/components/editable-media.mdx
  demo/react/layout/MainNav.tsx
  src/components/avatar/react/Avatar.tsx
  src/components/editable-media/angularjs/editable-media.html
  src/components/editable-media/angularjs/editable-media_directive.js
  src/components/editable-media/react/EditableMedia.test.tsx
  src/components/editable-media/react/EditableMedia.tsx
  src/components/editable-media/react/__snapshots__/EditableMedia.test.tsx.snap
  src/components/editable-media/style/lumapps/_index.scss
  src/components/thumbnail/react/Thumbnail.tsx
  src/core/utils.js
  src/react.index.ts
Labels: need: test

#173 feat(post-block): add light and dark theme variant for post-block meta and text
  CHANGELOG.react.md
  demo/react/doc/product/components/post-block.mdx
  src/components/post-block/style/lumapps/_index.scss
Labels: need: review-frontend, need: test

#178 chore: rework yeoman templates
  .eslintignore
  CONTRIBUTING.md
  package.json
  yarn.lock
  yo-generators/README.md
  yo-generators/generator-lumx-component/.eslintignore
  yo-generators/generator-lumx-component/.eslintrc.js
  yo-generators/generator-lumx-component/.travis.yml
  yo-generators/generator-lumx-component/.yo-rc.json
  yo-generators/generator-lumx-component/LICENSE
  yo-generators/generator-lumx-component/README.md
  yo-generators/generator-lumx-component/__tests__/app.js
  yo-generators/generator-lumx-component/__tests__/class-component.js
  yo-generators/generator-lumx-component/__tests__/component.js
  yo-generators/generator-lumx-component/__tests__/functional-component.js
  yo-generators/generator-lumx-component/__tests__/tests.js
  yo-generators/generator-lumx-component/generators/app/index.js
  yo-generators/generator-lumx-component/generators/component/index.js
  yo-generators/generator-lumx-component/generators/component/templates/ClassComponent.tsx.ejs
  yo-generators/generator-lumx-component/generators/component/templates/FunctionalComponent.tsx.ejs
  yo-generators/generator-lumx-component/generators/demo/index.js
  yo-generators/generator-lumx-component/generators/demo/templates/default.tsx.ejs
  yo-generators/generator-lumx-component/generators/demo/templates/index.tsx.ejs
  yo-generators/generator-lumx-component/jest.config.js
  yo-generators/generator-lumx-component/package.json
  yo-generators/generator-lumx-component/yarn.lock
  yo-generators/generators/component/index.js
  yo-generators/generators/component/templates/FunctionalComponent.tsx.ejs
  yo-generators/generators/demo/index.js
  yo-generators/generators/demo/templates/demo.mdx.ejs
  yo-generators/generators/index.js
  yo-generators/generators/tests/index.js
  yo-generators/generators/tests/templates/Component.test.tsx.ejs
  yo-generators/package.json
Labels: need: merge

#169 chore(sidenav): code cleanup
  CHANGELOG.react.md
  demo/react/components/side-navigation/default.tsx
  demo/react/components/side-navigation/index.tsx
  src/components/side-navigation/react/SideNavigation.test.tsx
  src/components/side-navigation/react/SideNavigation.tsx
  src/components/side-navigation/react/SideNavigationItem.tsx
Labels: need: merge

#124 docs(comment-block)
  demo/angularjs/components/comment-block/controller.js
  demo/angularjs/components/comment-block/demo.html
  demo/angularjs/components/comment-block/doc.md
  demo/angularjs/components/comment-block/partials/default.html
  demo/angularjs/components/comment-block/partials/relevant.html
  demo/angularjs/components/comment-block/partials/threaded.html
Labels: need: review-doc

#153 refactor(RadioButton): simplify props
  CHANGELOG.react.md
  demo/react/components/radio-button/default.tsx
  demo/react/components/radio-button/index.tsx
  demo/react/components/radio-button/with-helpers.tsx
  demo/react/doc/product/components/radio-button.mdx
  src/components/radio-button/react/RadioButton.test.tsx
  src/components/radio-button/react/RadioButton.tsx
  src/components/radio-button/react/RadioButtonHelper.test.tsx
  src/components/radio-button/react/RadioButtonHelper.tsx
  src/components/radio-button/react/RadioButtonLabel.test.tsx
  src/components/radio-button/react/RadioButtonLabel.tsx
  src/components/radio-button/react/RadioGroup.test.tsx
  src/components/radio-button/react/__snapshots__/RadioButton.test.tsx.snap
  src/components/radio-button/react/__snapshots__/RadioButtonHelper.test.tsx.snap
  src/components/radio-button/react/__snapshots__/RadioButtonLabel.test.tsx.snap
  src/components/radio-button/react/__snapshots__/RadioGroup.test.tsx.snap
  src/react.index.ts
Labels: need: test

#181 chore: update project dependencies
  package.json
  patches/@types+jest+24.0.11.patch
  src/components/editable-media/react/__snapshots__/EditableMedia.test.tsx.snap
  yarn.lock
Labels: need: review-frontend

#184 fix(asset-block): fix retina support for thumbnail in the block
  demo/react/layout/AssetBlock.tsx
Labels: need: review-frontend

#188 fix: rollback eslint & prettier package update that introduced errors
  package.json
  yarn.lock
Labels: need: review-frontend

#190 feat(thumbnail lazy loading): allow native chrome lazy loading on thumbnail images
  CHANGELOG.react.md
  src/components/thumbnail/react/Thumbnail.tsx
Labels: need: review-frontend, need: test

#161 feat(dialog): react component
  demo/react/doc/product/components/dialog.mdx
  demo/react/doc/product/components/lightbox.mdx
  src/components/dialog/react/Dialog.tsx
  src/components/index.ts
  src/components/lightbox/react/Lightbox.tsx
  src/core/react/hooks/useIntersectionObserver.tsx
  src/react.index.ts
Labels: need: test

#77 feat(notification): react component
  .gitignore
  demo/react/doc/product/components/notification.mdx
  src/components/chip/react/Chip.test.tsx
  src/components/notification/angularjs/notification_service.js
  src/components/notification/constants.ts
  src/components/notification/react/Notification.test.tsx
  src/components/notification/react/Notification.tsx
  src/components/notification/react/__snapshots__/Notification.test.tsx.snap
  src/core/package.json
  src/core/utils.js
  src/react.index.ts
Labels: need: merge, need: rebase

#196 feat(dialog): add is loading prop support
  src/components/dialog/angularjs/dialog.html
  src/components/dialog/angularjs/dialog_directive.js
  src/components/dialog/react/Dialog.tsx
  src/components/dialog/style/lumapps/_index.scss
Labels: need: test

#195 feat(react): handle custom colors
  demo/react/App.tsx
  demo/utils.d.ts
  src/components/button/react/ButtonRoot.tsx
  src/components/checkbox/react/Checkbox.tsx
  src/components/chip/react/Chip.tsx
  src/components/list/react/List.tsx
  src/components/progress/react/Progress.tsx
  src/components/radio-button/react/RadioButton.tsx
  src/components/select/react/Select.tsx
  src/components/side-navigation/react/SideNavigation.tsx
  src/components/slideshow/react/Slideshow.tsx
  src/components/switch/react/Switch.tsx
  src/components/tabs/react/Tabs.tsx
  src/components/text-field/react/TextField.tsx
Labels: need: test

#202 chore(release): release version 0.11.0 for @lumx/react
  CHANGELOG.react.md
  src/core/react/package.json
Labels: need: review-frontend

#201 fix(react-progress): fix property name
  CHANGELOG.react.md
  src/components/progress/react/Progress.tsx
Labels: need: review-frontend

#200 fix(textarea styles): Text area height and style fixes
  CHANGELOG.react.md
  demo/react/doc/product/components/text-field.mdx
  src/components/select/style/material/_index.scss
  src/components/text-field/angularjs/text-field_directive.js
  src/components/text-field/react/TextField.tsx
  src/components/text-field/react/__snapshots__/TextField.test.tsx.snap
  src/components/text-field/style/lumapps/_index.scss
  src/components/text-field/style/lumapps/_mixins.scss
  src/components/text-field/style/material/_index.scss
  src/components/text-field/style/material/_mixins.scss
Labels: need: review-integration, need: test

#199 feat(textfield-enhancements): Text field enhancements
  CHANGELOG.react.md
  demo/react/doc/product/components/chip.mdx
  demo/react/doc/product/components/text-field.mdx
  src/angularjs.index.js
  src/components/button/style/lumapps/_mixins.scss
  src/components/button/style/lumapps/_variables.scss
  src/components/button/style/material/_variables.scss
  src/components/chip/angularjs/chip-group_directive.js
  src/components/chip/react/ChipGroup.test.tsx
  src/components/chip/react/ChipGroup.tsx
  src/components/chip/react/__snapshots__/ChipGroup.test.tsx.snap
  src/components/chip/style/lumapps/_index.scss
  src/components/chip/style/lumapps/_variables.scss
  src/components/select/angularjs/select.html
  src/components/select/react/Select.tsx
  src/components/select/react/__snapshots__/Select.test.tsx.snap
  src/components/select/style/lumapps/_index.scss
  src/components/select/style/lumapps/_mixins.scss
  src/components/select/style/material/_index.scss
  src/components/text-field/angularjs/text-field.html
  src/components/text-field/angularjs/text-field_directive.js
  src/components/text-field/react/TextField.tsx
  src/components/text-field/react/__snapshots__/TextField.test.tsx.snap
  src/components/text-field/style/lumapps/_index.scss
  src/components/text-field/style/lumapps/_mixins.scss
  src/components/text-field/style/lumapps/_variables.scss
  src/components/text-field/style/material/_index.scss
  src/components/text-field/style/material/_mixins.scss
  src/core/custom-colors.js
  src/react.index.ts
Labels: need: test

#191 feat(autocomplete simple): react component for autocomplete - simple variation
  CHANGELOG.react.md
  demo/react/doc/product/components/autocomplete.mdx
  demo/react/layout/MainNav.tsx
  src/components/autocomplete/react/Autocomplete.test.tsx
  src/components/autocomplete/react/Autocomplete.tsx
  src/components/autocomplete/react/__snapshots__/Autocomplete.test.tsx.snap
  src/components/list/react/List.tsx
  src/components/list/react/ListItem.tsx
  src/components/list/style/lumapps/_index.scss
  src/components/list/style/lumapps/_mixins.scss
  src/core/react/hooks/index.tsx
  src/core/react/hooks/useKeyboardListNavigation.tsx
  src/react.index.ts
Labels: need: test

#206 feat(build): generate typescript declaration file for NPM @lumx/react package
  CHANGELOG.react.md
  demo/react/components/dropdown/default.tsx
  demo/react/components/dropdown/index.tsx
  demo/react/components/dropdown/target.tsx
  demo/react/layout/AssetBlock.tsx
  demo/react/layout/MainNav.tsx
  package.json
  src/components/button/react/Button.tsx
  src/components/button/react/ButtonGroup.tsx
  src/components/button/react/IconButton.tsx
  src/components/icon/react/Icon.tsx
  src/components/radio-button/react/RadioGroup.tsx
  src/components/side-navigation/react/SideNavigation.tsx
  src/components/side-navigation/react/SideNavigationItem.tsx
  src/components/tabs/react/Tabs.tsx
  src/components/thumbnail/react/Thumbnail.tsx
  src/core/react/utils/calculatePopoverPlacement.ts
  webpack/react/webpack.prod.js
  webpack/webpack.config.js
  yarn.lock
Labels: need: review-frontend

#210 Release @lumx/react v0.12.0
  CHANGELOG.react.md
  src/core/react/package.json
Labels: need: review-frontend
