Repository lumapps/design-system, pull requests merged in 2019-06, with the labels that each got.

#75 Added arrow on tooltip
  demo/react/components/popover/tooltip.tsx
  src/components/popover/react/Popover.tsx
Labels: need: dev-integration

#79 feat(Checkbox): add new component
  demo/react/components/checkbox/default.tsx
  demo/react/components/checkbox/index.tsx
  src/components/checkbox/react/Checkbox.test.tsx
  src/components/checkbox/react/Checkbox.tsx
  src/components/checkbox/react/CheckboxHelper.test.tsx
  src/components/checkbox/react/CheckboxHelper.tsx
  src/components/checkbox/react/CheckboxLabel.test.tsx
  src/components/checkbox/react/CheckboxLabel.tsx
  src/components/checkbox/react/__snapshots__/Checkbox.test.tsx.snap
  src/components/checkbox/react/__snapshots__/CheckboxHelper.test.tsx.snap
  src/components/checkbox/react/__snapshots__/CheckboxLabel.test.tsx.snap
  src/react.index.ts
Labels: need: test

#81 fix(react-tooltip): update position on opening
  src/components/tooltip/react/Tooltip.tsx
Labels: need: review-frontend

#69 feat(chip): add color support
  demo/react/components/chip/default.tsx
  src/components/button/style/lumapps/_index.scss
  src/components/chip/angularjs/chip.html
  src/components/chip/angularjs/chip_directive.js
  src/components/chip/react/Chip.tsx
  src/components/chip/react/__snapshots__/Chip.test.tsx.snap
  src/components/chip/style/lumapps/_index.scss
Labels: need: test

#70 feat(thumbnail): add align parameter support
  demo/angularjs/components/image-block/partials/image-block-alignment.html
  demo/angularjs/components/lightbox/demo.html
  demo/react/components/image-block/default.tsx
  src/components/image-block/angularjs/image-block.html
  src/components/image-block/angularjs/image-block_directive.js
  src/components/image-block/react/ImageBlock.tsx
  src/components/image-block/style/lumapps/_index.scss
  src/components/index.ts
  src/components/thumbnail/angularjs/thumbnail.html
  src/components/thumbnail/angularjs/thumbnail_directive.js
  src/components/thumbnail/react/Thumbnail.tsx
  src/components/thumbnail/style/lumapps/_index.scss
Labels: need: test

#85 feat(icon): add reference handling
  src/components/icon/react/Icon.tsx
Labels: need: review-frontend

#84 fix(image-block): remove useless export
  demo/react/components/lightbox/default.tsx
  src/react.index.ts
Labels: need: review-frontend

#86 Create dedicated core package and add icon publishing
  README.md
  package.json
  src/core/angularjs/README.md
  src/core/angularjs/package.json
  src/core/package.json
  src/core/react/README.md
  src/core/react/package.json
  src/icons/package.json
  webpack/angularjs/webpack.config.js
  webpack/angularjs/webpack.dev.js
  webpack/angularjs/webpack.prod.js
  webpack/angularjs/webpack.umd.js
  webpack/constants.js
  webpack/core/webpack.config.js
  webpack/core/webpack.prod.js
  webpack/react/webpack.config.js
  webpack/react/webpack.dev.js
  webpack/react/webpack.prod.js
  webpack/react/webpack.umd.js
  webpack/utils.js
  webpack/webpack.build.utils.js
  webpack/webpack.dev.utils.js
Labels: need: review-frontend

#83 fix(table): avoid bad style on header with long label
  src/components/table/angularjs/table-cell-head.html
  src/components/table/react/TableCell.tsx
  src/components/table/style/lumapps/_index.scss
Labels: need: review-frontend
