Repository lumapps/design-system, pull requests merged in 2020-12, with the labels that each got.

#558 [Link] Add right and left icons LUM-13298
  CHANGELOG.md
  packages/lumx-core/src/scss/components/link/lumapps/_index.scss
  packages/lumx-core/src/scss/components/link/lumapps/_mixins.scss
  packages/lumx-react/src/components/link/Link.stories.tsx
  packages/lumx-react/src/components/link/Link.tsx
  packages/lumx-react/src/components/link/__snapshots__/Link.test.tsx.snap
  packages/site-demo/content/product/components/link/react/default.tsx
  packages/site-demo/content/product/components/link/react/implicit.tsx
  packages/site-demo/content/product/components/link/react/sizes.tsx
Labels: need: merge

#564 chore(storybook): add source code addon
  packages/lumx-react/.storybook/main.js
  packages/lumx-react/package.json
  yarn.lock
Labels: need: review-frontend

#560 Fix popover bugs
  CHANGELOG.md
  packages/lumx-core/src/scss/components/popover/lumapps/_index.scss
  packages/lumx-react/package.json
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/components/popover/Popover.stories.tsx
  packages/lumx-react/src/components/popover/Popover.tsx
  yarn.lock
Labels: need: test

#556 fix(list): forward on item selected event
  CHANGELOG.md
  packages/lumx-core/src/js/utils.ts
  packages/lumx-react/src/components/list/List.tsx
  packages/lumx-react/src/components/list/ListItem.tsx
  packages/lumx-react/src/components/list/useInteractiveList.tsx
Labels: need: review-frontend

#567 Merge release v0.28.1 into master
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-core/src/js/utils.ts
  packages/lumx-core/src/scss/components/popover/lumapps/_index.scss
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/components/list/List.tsx
  packages/lumx-react/src/components/list/ListItem.tsx
  packages/lumx-react/src/components/list/useInteractiveList.tsx
  packages/lumx-react/src/components/popover/Popover.stories.tsx
  packages/lumx-react/src/components/popover/Popover.tsx
  packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#298 refactor: improve layers management
  packages/lumx-angularjs/src/components/dialog/dialog_directive.js
  packages/lumx-angularjs/src/components/dropdown/dropdown_directive.js
  packages/lumx-angularjs/src/components/lightbox/lightbox_directive.js
  packages/lumx-angularjs/src/components/notification/notification_service.js
  packages/lumx-angularjs/src/components/popover/popover_directive.js
  packages/lumx-angularjs/src/lumx.js
  packages/lumx-angularjs/src/utils/depth_service.js
  packages/lumx-angularjs/src/utils/index.js
  packages/lumx-core/src/scss/components/dialog/lumapps/_index.scss
  packages/lumx-core/src/scss/components/dropdown/lumapps/_index.scss
  packages/lumx-core/src/scss/components/lightbox/lumapps/_index.scss
  packages/lumx-core/src/scss/components/notification/lumapps/_index.scss
  packages/lumx-core/src/scss/components/popover/lumapps/_index.scss
  packages/lumx-core/src/scss/components/tooltip/lumapps/_index.scss
  packages/lumx-core/src/scss/core/base/lumapps/_variables.scss
Labels: need: test

#571 feat(comment-block): add header actions prop
  CHANGELOG.md
  packages/lumx-angularjs/src/components/comment-block/comment-block.html
  packages/lumx-core/src/scss/components/comment-block/lumapps/_index.scss
  packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
  packages/lumx-react/src/components/comment-block/CommentBlock.tsx
  packages/site-demo/content/product/components/comment-block/react/threaded.tsx
Labels: need: review-frontend, need: review-integration, need: test

#537 docs(button): updated doc with toggle case
  packages/site-demo/content/product/components/button/index.mdx
  packages/site-demo/content/product/components/button/react/toggle.tsx
Labels: need: merge

#538 docs(sizes): added sizes documentation
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/components/avatar/index.mdx
  packages/site-demo/content/product/components/icon/index.mdx
  packages/site-demo/content/product/components/thumbnail/index.mdx
  packages/site-demo/content/product/components/user-block/index.mdx
  packages/site-demo/content/product/foundations/size/index.mdx
  packages/site-demo/content/product/foundations/size/react/abstract-example.tsx
  packages/site-demo/content/product/foundations/size/react/t-shirt-example.tsx
  packages/site-demo/src/style/layout/main/_main.scss
Labels: need: merge

#559 feat(skeleton): create circle, rectangular and typography variants
  CHANGELOG.md
  packages/lumx-core/src/scss/components/skeleton/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-react/src/components/index.ts
  packages/lumx-react/src/components/skeleton/Skeleton.stories.tsx
  packages/lumx-react/src/components/skeleton/SkeletonCircle.tsx
  packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx
  packages/lumx-react/src/components/skeleton/SkeletonTypography.tsx
  packages/lumx-react/src/index.ts
  packages/site-demo/content/product/components/skeleton/index.mdx
  packages/site-demo/content/product/components/skeleton/react/animation.tsx
  packages/site-demo/content/product/components/skeleton/react/circle.tsx
  packages/site-demo/content/product/components/skeleton/react/rectangle.tsx
  packages/site-demo/content/product/components/skeleton/react/typography.tsx
Labels: need: merge

#573 fix(site-demo): fix theme switcher bug
  packages/site-demo/src/global-theme/theme-switcher.ts
Labels: need: review-frontend

#576 merge 0.28.2 into master
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-angularjs/src/components/comment-block/comment-block.html
  packages/lumx-core/package.json
  packages/lumx-core/src/scss/components/comment-block/lumapps/_index.scss
  packages/lumx-core/src/scss/components/skeleton/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
  packages/lumx-react/src/components/comment-block/CommentBlock.tsx
  packages/lumx-react/src/components/index.ts
  packages/lumx-react/src/components/skeleton/Skeleton.stories.tsx
  packages/lumx-react/src/components/skeleton/SkeletonCircle.tsx
  packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx
  packages/lumx-react/src/components/skeleton/SkeletonTypography.tsx
  packages/lumx-react/src/components/skeleton/index.ts
  packages/lumx-react/src/index.ts
  packages/lumx-react/src/stories/generated/Button/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Button/toggle.tsx
  packages/lumx-react/src/stories/generated/Skeleton/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Skeleton/animation.tsx
  packages/lumx-react/src/stories/generated/Skeleton/circle.tsx
  packages/lumx-react/src/stories/generated/Skeleton/rectangle.tsx
  packages/lumx-react/src/stories/generated/Skeleton/typography.tsx
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/components/avatar/index.mdx
  packages/site-demo/content/product/components/button/index.mdx
  packages/site-demo/content/product/components/button/react/toggle.tsx
  packages/site-demo/content/product/components/comment-block/react/threaded.tsx
  packages/site-demo/content/product/components/icon/index.mdx
  packages/site-demo/content/product/components/skeleton/index.mdx
  packages/site-demo/content/product/components/skeleton/react/animation.tsx
  packages/site-demo/content/product/components/skeleton/react/circle.tsx
  packages/site-demo/content/product/components/skeleton/react/rectangle.tsx
  packages/site-demo/content/product/components/skeleton/react/typography.tsx
  packages/site-demo/content/product/components/thumbnail/index.mdx
  packages/site-demo/content/product/components/user-block/index.mdx
  packages/site-demo/content/product/foundations/size/index.mdx
  packages/site-demo/content/product/foundations/size/react/abstract-example.tsx
  packages/site-demo/content/product/foundations/size/react/t-shirt-example.tsx
  packages/site-demo/package.json
  packages/site-demo/src/style/layout/main/_main.scss
  packages/yo-generators/package.json
Labels: need: review-frontend

#572 fix/lightbox LUM-11248
  CHANGELOG.md
  packages/lumx-core/src/scss/components/lightbox/lumapps/_index.scss
  packages/lumx-react/package.json
  packages/lumx-react/src/components/dialog/Dialog.tsx
  packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
  packages/lumx-react/src/components/image-block/ImageBlock.tsx
  packages/lumx-react/src/components/lightbox/Lightbox.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/hooks/useDisableBodyScroll.ts
  packages/site-demo/content/product/components/image-block/react/image-block-alignment.tsx
  packages/site-demo/content/product/foundations/size/react/t-shirt-example.tsx
  yarn.lock
Labels: need: review-frontend

#569 chore(build): new lumx react build LUM-11801
  CHANGELOG.md
  configs/babel.config.js
  package.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-react/.storybook/story-block/StoryBlock.tsx
  packages/lumx-react/.storybook/webpack.config.js
  packages/lumx-react/jest/transform.js
  packages/lumx-react/package.json
  packages/lumx-react/rollup.config.js
  packages/lumx-react/src/components/select/Select.test.tsx
  packages/lumx-react/src/components/select/SelectMultiple.test.tsx
  packages/lumx-react/src/components/select/WithSelectContext.tsx
  packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
  packages/lumx-react/src/components/select/__snapshots__/SelectMultiple.test.tsx.snap
  packages/lumx-react/src/components/slider/Slider.tsx
  packages/lumx-react/src/components/switch/Switch.test.tsx
  packages/lumx-react/src/components/switch/Switch.tsx
  packages/lumx-react/src/components/switch/__snapshots__/Switch.test.tsx.snap
  packages/lumx-react/src/components/tabs/state.ts
  packages/lumx-react/src/components/text-field/TextField.tsx
  packages/lumx-react/src/components/tooltip/Tooltip.test.tsx
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
  packages/lumx-react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/lumx-react/webpack.config.js
  yarn.lock
Labels: need: review-frontend

#581 fix(switch): prevent content to take parent full width LUM-12987
  CHANGELOG.md
  packages/lumx-core/src/scss/components/switch/lumapps/_index.scss
  packages/lumx-react/src/stories/generated/Mosaic/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Mosaic/four-images.tsx
  packages/lumx-react/src/stories/generated/Mosaic/more-images.tsx
  packages/lumx-react/src/stories/generated/Mosaic/three-images.tsx
  packages/lumx-react/src/stories/generated/Mosaic/two-images.tsx
Labels: need: review-frontend

#580 chore(ci): build chromatic on tag rather than on push branch
  .github/workflows/chromatic.yaml
Labels: need: merge

#549 docs(loading-state): added doc and nav entry
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/patterns/loading-state/assets/progress-case.png
  packages/site-demo/content/product/patterns/loading-state/assets/progress-dialog.png
  packages/site-demo/content/product/patterns/loading-state/assets/progress-page.png
  packages/site-demo/content/product/patterns/loading-state/assets/progress-user.png
  packages/site-demo/content/product/patterns/loading-state/assets/skeleton-menu.png
  packages/site-demo/content/product/patterns/loading-state/assets/skeleton-result.png
  packages/site-demo/content/product/patterns/loading-state/assets/skeleton-users.png
  packages/site-demo/content/product/patterns/loading-state/assets/skeleton-widget.png
  packages/site-demo/content/product/patterns/loading-state/index.mdx
Labels: need: review-doc

#585 fix(select): forward-props
  CHANGELOG.md
  packages/lumx-react/src/components/select/Select.test.tsx
  packages/lumx-react/src/components/select/Select.tsx
Labels: need: review-frontend
