Repository lumapps/design-system, pull requests merged in 2020-11, with the labels that each got.

#550 chore(changelog): fix error in changelog
  CHANGELOG.md
Labels: need: review-frontend

#547 chore(click-away): fix ClickAwayProvider initialization error
  CHANGELOG.md
  packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx
Labels: need: review-frontend

#539 refactor(link): add button alternative and typo prop LUM-11250
  CHANGELOG.md
  packages/lumx-core/src/scss/components/link/lumapps/_mixins.scss
  packages/lumx-react/src/components/button/Button.stories.tsx
  packages/lumx-react/src/components/button/ButtonRoot.tsx
  packages/lumx-react/src/components/index.ts
  packages/lumx-react/src/components/link/Link.stories.tsx
  packages/lumx-react/src/components/link/Link.test.tsx
  packages/lumx-react/src/components/link/Link.tsx
  packages/lumx-react/src/components/link/__snapshots__/Link.test.tsx.snap
Labels: need: merge

#540 refactor(tabs): separate panels from tabs and improve a11y LUM-11309
  CHANGELOG.md
  packages/lumx-core/src/scss/components/tabs/lumapps/_index.scss
  packages/lumx-core/src/scss/components/tabs/lumapps/_mixins.scss
  packages/lumx-react/src/components/tabs/Tab.test.tsx
  packages/lumx-react/src/components/tabs/Tab.tsx
  packages/lumx-react/src/components/tabs/TabList.test.tsx
  packages/lumx-react/src/components/tabs/TabList.tsx
  packages/lumx-react/src/components/tabs/TabPanel.test.tsx
  packages/lumx-react/src/components/tabs/TabPanel.tsx
  packages/lumx-react/src/components/tabs/TabProvider.test.tsx
  packages/lumx-react/src/components/tabs/TabProvider.tsx
  packages/lumx-react/src/components/tabs/Tabs.stories.tsx
  packages/lumx-react/src/components/tabs/Tabs.tsx
  packages/lumx-react/src/components/tabs/__snapshots__/Tab.test.tsx.snap
  packages/lumx-react/src/components/tabs/__snapshots__/TabList.test.tsx.snap
  packages/lumx-react/src/components/tabs/__snapshots__/TabPanel.test.tsx.snap
  packages/lumx-react/src/components/tabs/__snapshots__/Tabs.test.tsx.snap
  packages/lumx-react/src/components/tabs/state.test.tsx
  packages/lumx-react/src/components/tabs/state.ts
  packages/lumx-react/src/components/tabs/test.mocks.ts
  packages/lumx-react/src/hooks/useRovingTabIndex.tsx
  packages/lumx-react/src/index.ts
  packages/site-demo/content/product/components/tabs/index.mdx
  packages/site-demo/content/product/components/tabs/react/default.tsx
  packages/site-demo/content/product/components/tabs/react/icon-tabs.tsx
  packages/site-demo/content/product/components/tabs/react/left-tabs.tsx
Labels: need: merge

#542 refactor(image-block-and-mosaic): move thumbnail props
  CHANGELOG.md
  packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
  packages/lumx-react/src/components/image-block/ImageBlock.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.test.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.tsx
  packages/lumx-react/src/components/post-block/Demos.stories.tsx
  packages/lumx-react/src/components/post-block/demos
  packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
  packages/site-demo/content/product/components/image-block/react/default.tsx
  packages/site-demo/content/product/components/image-block/react/image-block-above.tsx
  packages/site-demo/content/product/components/image-block/react/image-block-alignment.tsx
  packages/site-demo/content/product/components/image-block/react/image-block-padding.tsx
  packages/site-demo/content/product/components/slideshow/react/auto.tsx
  packages/site-demo/content/product/components/slideshow/react/default.tsx
  packages/site-demo/content/product/components/slideshow/react/group.tsx
Labels: need: test
