Repository lumapps/design-system, pull requests merged in 2020-04, with the labels that each got.

#368 fix(tooltip): rounding coordinates in integer for sharper display
  CHANGELOG.md
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
Labels: need: review-frontend

#367 feat(link): add link ref on Link React component
  CHANGELOG.md
  packages/lumx-react/src/components/link/Link.test.tsx
  packages/lumx-react/src/components/link/Link.tsx
Labels: need: review-frontend

#370 chore(release): release v0.21.15
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#372 feat(side-navigation-item-link): add props to link in side nav item
  CHANGELOG.md
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
Labels: need: review-frontend

#374 feat: declare @lumx/react, @lumx/icons and @lumx/core as side-effect free
  CHANGELOG.md
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
Labels: need: review-frontend

#379 feat(link-preview): rename web bookmark and add render conditions
  CHANGELOG.md
  packages/lumx-core/src/scss/components/link-preview/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-react/src/components/link-preview/LinkPreview.stories.tsx
  packages/lumx-react/src/components/link-preview/LinkPreview.test.tsx
  packages/lumx-react/src/components/link-preview/LinkPreview.tsx
  packages/lumx-react/src/components/link-preview/__snapshots__/LinkPreview.test.tsx.snap
  packages/lumx-react/src/components/web-bookmark/__snapshots__/WebBookmark.test.tsx.snap
  packages/lumx-react/src/index.ts
Labels: need: review-design, need: review-frontend

#380 docs: add split select breaking change into CHANGELOG
  CHANGELOG.md
Labels: need: review-frontend

#381 feat(dialog): only use css for scrollable dialog
  CHANGELOG.md
  packages/lumx-angularjs/src/components/dialog/dialog.html
  packages/lumx-angularjs/src/components/dialog/dialog_directive.js
  packages/lumx-core/src/scss/components/dialog/lumapps/_index.scss
  packages/lumx-react/src/components/dialog/Dialog.tsx
Labels: need: review-frontend

#385 fix(infinite-scroll): trigger infinite when container is fully displayed
  CHANGELOG.md
  packages/lumx-react/src/components/select/Select.stories.tsx
  packages/lumx-react/src/hooks/useInfiniteScroll.tsx
Labels: need: test
