Repository lumapps/design-system, pull requests merged in 2020-10, with the labels that each got.

#446 feat(demo-site): update datepicker demo and add prop table
  packages/site-demo/content/product/components/date-picker/index.mdx
  packages/site-demo/content/product/components/date-picker/react/no-past-date-allowed.tsx
  packages/site-demo/content/product/components/date-picker/react/past-date-allowed.tsx
Labels: need: rebase, need: review-doc, need: test

#309 docs(textfield): updated doc
  packages/site-demo/content/product/components/text-field/index.mdx
  packages/site-demo/content/product/components/text-field/react/character-counter.tsx
  packages/site-demo/content/product/components/text-field/react/clearable.tsx
  packages/site-demo/content/product/components/text-field/react/default.tsx
  packages/site-demo/content/product/components/text-field/react/helper.tsx
  packages/site-demo/content/product/components/text-field/react/invalid.tsx
  packages/site-demo/content/product/components/text-field/react/placeholder.tsx
  packages/site-demo/content/product/components/text-field/react/text-area-invalid.tsx
  packages/site-demo/content/product/components/text-field/react/text-area-valid.tsx
  packages/site-demo/content/product/components/text-field/react/text-area.tsx
  packages/site-demo/content/product/components/text-field/react/valid.tsx
Labels: need: review-doc

#305 docs(select): updated texts
  packages/site-demo/content/product/components/select/index.mdx
  packages/site-demo/content/product/components/select/react/multi-select-chip.tsx
  packages/site-demo/content/product/components/select/react/multi-select-search.tsx
  packages/site-demo/content/product/components/select/react/multi-select.tsx
  packages/site-demo/content/product/components/select/react/select-chip.tsx
  packages/site-demo/content/product/components/select/react/single-select.tsx
  packages/site-demo/content/product/components/select/react/state-disabled.tsx
  packages/site-demo/content/product/components/select/react/state-invalid.tsx
  packages/site-demo/content/product/components/select/react/state-valid.tsx
  packages/site-demo/content/product/components/select/react/validation-invalid.tsx
  packages/site-demo/content/product/components/select/react/validation-valid.tsx
Labels: need: review-frontend, need: test

#303 docs(chip): updated doc
  packages/site-demo/content/product/components/chip/index.mdx
  packages/site-demo/content/product/components/chip/react/default.tsx
  packages/site-demo/content/product/components/chip/react/filter.tsx
  packages/site-demo/content/product/components/chip/react/group.tsx
  packages/site-demo/content/product/components/chip/react/small.tsx
Labels: need: review-doc

#289 docs(badge): implement badge react component to demo
  packages/site-demo/content/product/components/badge/react/icon.tsx
  packages/site-demo/content/product/components/badge/react/label.tsx
  packages/site-demo/content/product/components/badge/react/thumbnail.tsx
Labels: in progress

#492 docs(link-preview): added nav entry and doc
  packages/lumx-react/src/components/link-preview/Demos.stories.tsx
  packages/site-demo/content/product/components/link-preview/index.mdx
  packages/site-demo/content/product/components/link-preview/react/.gitkeep
  packages/site-demo/content/product/components/link-preview/react/default.tsx
  packages/site-demo/src/components/layout/MainNav.tsx
Labels: need: doc-update

#499 chore(site-demo): display the lumx version on component demo pages
  packages/site-demo/src/components/LumxVersion.tsx
  packages/site-demo/src/components/layout/Main.tsx
  packages/site-demo/src/index.html.ejs
  packages/site-demo/webpack.config.js
Labels: need: merge

#506 feat(flexbox): add gap property
  CHANGELOG.md
  packages/lumx-core/src/scss/components/flex-box/lumapps/_index.scss
  packages/lumx-react/src/components/flex-box/FlexBox.tsx
Labels: need: review-frontend

#507 feat(divider): add has divider helper
  CHANGELOG.md
  packages/lumx-core/src/scss/components/dialog/lumapps/_index.scss
  packages/lumx-core/src/scss/components/divider/lumapps/_index.scss
  packages/lumx-core/src/scss/components/divider/lumapps/_mixins.scss
  packages/lumx-core/src/scss/components/divider/lumapps/_variables.scss
  packages/lumx-core/src/scss/components/tabs/lumapps/_index.scss
  packages/lumx-core/src/scss/core/base/lumapps/_variables.scss
  packages/site-demo/src/style/components/_design-token.scss
Labels: need: review-integration

#292 docs(filter-sort): page content
  packages/site-demo/content/product/patterns/filter-and sort/assets/filter-and-sort-anatomy.png
  packages/site-demo/content/product/patterns/filter-and sort/index.mdx
  packages/site-demo/content/product/patterns/filter-and sort/react/choices.tsx
  packages/site-demo/content/product/patterns/filter-and sort/react/collapsed.tsx
  packages/site-demo/content/product/patterns/filter-and sort/react/facets.tsx
  packages/site-demo/content/product/patterns/filter-and sort/react/responsive.tsx
  packages/site-demo/content/product/patterns/filter-and sort/react/sorting.tsx
  packages/site-demo/content/product/patterns/filter-and sort/react/text.tsx
  packages/site-demo/content/product/patterns/filter-and sort/react/vertical.tsx
  packages/site-demo/src/components/layout/MainNav.tsx
Labels: in progress

#509 chore(link-a11y): add `linkAs` prop on component with links
  CHANGELOG.md
  packages/lumx-react/src/components/link/Link.stories.tsx
  packages/lumx-react/src/components/link/Link.tsx
  packages/lumx-react/src/components/list/ListItem.stories.tsx
  packages/lumx-react/src/components/list/ListItem.tsx
  packages/lumx-react/src/components/list/__snapshots__/ListItem.test.tsx.snap
  packages/lumx-react/src/components/side-navigation/SideNavigation.stories.tsx
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
  packages/lumx-react/src/utils/renderLink.tsx
Labels: hacktoberfest-accepted, need: review-frontend

#510 docs(filter-and-sort): fix text
  packages/site-demo/content/product/patterns/filter-and sort/index.mdx
Labels: need: review-doc

#512 docs(link-preview): added theme switcher on demo
  packages/site-demo/content/product/components/link-preview/index.mdx
Labels: need: review-doc

#514 chore(release): release v0.26.0
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: hacktoberfest-accepted, need: review-frontend

#516 chore(release): release v0.26.1
  .eslintrc.js
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/font.scss
  packages/lumx-icons/index.d.ts
  packages/lumx-icons/index.js
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/content/product/components/uploader/angularjs/controller.js
  packages/site-demo/content/product/components/uploader/react/default.tsx
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: hacktoberfest-accepted, need: review-frontend

#515 docs(link): updated text and demo blocks
  packages/site-demo/content/product/components/link/index.mdx
  packages/site-demo/content/product/components/link/react/default.tsx
  packages/site-demo/content/product/components/link/react/implicit.tsx
  packages/site-demo/content/product/components/link/react/sizes.tsx
Labels: need: review-doc, need: review-integration

#518 docs(link-preview): added big size docs
  packages/site-demo/content/product/components/link-preview/index.mdx
  packages/site-demo/content/product/components/link-preview/react/big.tsx
Labels: need: review-doc

#519 docs(textfield): updated docs text
  packages/site-demo/content/product/components/text-field/index.mdx
  packages/site-demo/content/product/components/text-field/react/required.tsx
Labels: need: review-doc

#520 chore(stories): fix broken stories
  packages/lumx-react/src/components/dialog/Demos.stories.tsx
  packages/lumx-react/src/components/image-block/Demos.stories.tsx
  packages/lumx-react/src/components/progress-tracker/Demos.stories.tsx
Labels: hacktoberfest-accepted, need: review-frontend

#523 chore(link): make `Link` prop type more permissive
  CHANGELOG.md
  packages/lumx-react/src/components/link/Link.tsx
Labels: hacktoberfest-accepted, need: review-frontend

#524 chore(button): add `linkAs` prop for better link a11y
  CHANGELOG.md
  packages/lumx-react/src/components/button/ButtonRoot.test.tsx
  packages/lumx-react/src/components/button/ButtonRoot.tsx
  packages/lumx-react/src/components/button/__snapshots__/ButtonRoot.test.tsx.snap
Labels: hacktoberfest-accepted, need: review-frontend

#526 chore(button): make button display a link when linkAs is set
  packages/lumx-react/src/components/button/ButtonRoot.tsx
Labels: need: review-frontend

#522 fix(list-item): link props
  CHANGELOG.md
  packages/lumx-react/src/components/list/ListItem.tsx
Labels: hacktoberfest-accepted, need: merge

#529 chore: fix storybook dependencies & imports
  packages/lumx-react/src/components/autocomplete/Demos.stories.tsx
  packages/lumx-react/src/components/avatar/Demos.stories.tsx
  packages/lumx-react/src/components/button/Demos.stories.tsx
  packages/lumx-react/src/components/checkbox/Demos.stories.tsx
  packages/lumx-react/src/components/chip/Chip.tsx
  packages/lumx-react/src/components/chip/Demos.stories.tsx
  packages/lumx-react/src/components/comment-block/Demos.stories.tsx
  packages/lumx-react/src/components/dialog/Demos.stories.tsx
  packages/lumx-react/src/components/divider/Demos.stories.tsx
  packages/lumx-react/src/components/dropdown/Demos.stories.tsx
  packages/lumx-react/src/components/expansion-panel/Demos.stories.tsx
  packages/lumx-react/src/components/image-block/Demos.stories.tsx
  packages/lumx-react/src/components/lightbox/Demos.stories.tsx
  packages/lumx-react/src/components/link-preview/Demos.stories.tsx
  packages/lumx-react/src/components/list/Demos.stories.tsx
  packages/lumx-react/src/components/notification/Demos.stories.tsx
  packages/lumx-react/src/components/popover/Demos.stories.tsx
  packages/lumx-react/src/components/progress-tracker/Demos.stories.tsx
  packages/lumx-react/src/components/progress-tracker/ProgressTracker.tsx
  packages/lumx-react/src/components/progress-tracker/ProgressTrackerStep.tsx
  packages/lumx-react/src/components/progress/Demos.stories.tsx
  packages/lumx-react/src/components/radio-button/Demos.stories.tsx
  packages/lumx-react/src/components/select/Demos.stories.tsx
  packages/lumx-react/src/components/side-navigation/Demos.stories.tsx
  packages/lumx-react/src/components/slider/Demos.stories.tsx
  packages/lumx-react/src/components/slideshow/Demos.stories.tsx
  packages/lumx-react/src/components/switch/Demos.stories.tsx
  packages/lumx-react/src/components/table/Demos.stories.tsx
  packages/lumx-react/src/components/table/TableRow.tsx
  packages/lumx-react/src/components/tabs/Demos.stories.tsx
  packages/lumx-react/src/components/tabs/Tab.tsx
  packages/lumx-react/src/components/text-field/Demos.stories.tsx
  packages/lumx-react/src/components/thumbnail/Demos.stories.tsx
  packages/lumx-react/src/components/toolbar/Demos.stories.tsx
  packages/lumx-react/src/components/tooltip/Demos.stories.tsx
  packages/lumx-react/src/components/uploader/Demos.stories.tsx
  packages/lumx-react/src/components/user-block/Demos.stories.tsx
  packages/site-demo/package.json
  yarn.lock
Labels: hacktoberfest-accepted, need: review-frontend

#530 chore(site-demo): update and fix MDX dependency resolution
  packages/site-demo/package.json
  packages/site-demo/src/components/CodeBlock/CodeBlock.tsx
  packages/site-demo/src/wrapRootElement.tsx
  packages/site-demo/untypped-modules.d.ts
  yarn.lock
Labels: need: review-frontend

#528 chore(slideshow-controls): export component
  CHANGELOG.md
  packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
  packages/lumx-react/src/index.ts
Labels: hacktoberfest-accepted

#531 fix(list): fix infinite loop on keyboard navigation
  CHANGELOG.md
  packages/lumx-react/src/components/list/List.stories.tsx
  packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap
  packages/lumx-react/src/components/list/useInteractiveList.tsx
Labels: hacktoberfest-accepted, need: review-frontend, need: test

#532 release/0.26.2
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#533 chore(site-demo): fix 404 nginx configuration
  .docker/nginx.conf
Labels: need: review-frontend
