Repository lumapps/design-system, pull requests merged in 2020-02, with the labels that each got.

#317 feat(table): add isClickable and isSelected missing props
  CHANGELOG.md
  packages/lumx-react/src/components/table/TableRow.tsx
Labels: need: review-frontend

#319 feat(table-row): add isDisabled prop
  CHANGELOG.md
  packages/lumx-angularjs/src/components/table/table-row.html
  packages/lumx-angularjs/src/components/table/table-row_directive.js
  packages/lumx-core/src/scss/components/table/lumapps/_index.scss
  packages/lumx-react/src/components/table/TableRow.tsx
Labels: need: test

#323 chore(release): release v0.21.5
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#324 fix(storybook): fix config with tsconfig paths resolve
  configs/ignore-not-found-export.js
  packages/lumx-react/.storybook/webpack.config.js
  packages/lumx-react/webpack.config.js
  packages/site-demo/webpack.config.js
Labels: need: test

#326 feat: add required prop to select and text-field components
  CHANGELOG.md
  packages/lumx-angularjs/src/components/input-label/input-label_directive.js
  packages/lumx-angularjs/src/components/select/select.html
  packages/lumx-angularjs/src/components/select/select_directive.js
  packages/lumx-angularjs/src/components/text-field/text-field.html
  packages/lumx-angularjs/src/components/text-field/text-field_directive.js
  packages/lumx-core/src/scss/components/input-label/lumapps/_index.scss
  packages/lumx-core/src/scss/components/input-label/lumapps/_mixins.scss
  packages/lumx-react/src/components/input-label/InputLabel.tsx
  packages/lumx-react/src/components/select/Select.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: review-frontend

#327 Fix/date picker
  CHANGELOG.md
  packages/lumx-core/src/js/date-picker.ts
  packages/lumx-react/src/components/date-picker/DatePicker.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.tsx
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerControlled.test.tsx.snap
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: review-frontend

#325 Feat/focal point react
  packages/lumx-core/src/scss/components/thumbnail/lumapps/_index.scss
  packages/lumx-react/src/components/thumbnail/FocusedImage.ts
  packages/lumx-react/src/components/thumbnail/IFocusedImageOptions.ts
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/components/thumbnail/useFocusedImage.tsx
Labels: need: test

#329 chore: update changelog
  CHANGELOG.md
Labels: need: review-doc

#321 chore(button): add knobs on simple button story
  packages/lumx-react/src/components/button/Button.stories.tsx
  packages/lumx-react/src/components/button/Button.tsx
  packages/lumx-react/src/components/button/ButtonRoot.tsx
Labels: need: review-frontend

#333 feat(react-image-block): add new props from Thumbnail component
  CHANGELOG.md
  packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
  packages/lumx-react/src/components/image-block/ImageBlock.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/index.ts
Labels: need: test

#335 chore(release): release v0.21.8
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#334 feat(notification): prevent showing notification when !isOpen
  CHANGELOG.md
  packages/lumx-angularjs/src/components/dialog/dialog_directive.js
  packages/lumx-angularjs/src/components/notification/notification_service.js
  packages/lumx-core/src/js/constants.ts
  packages/lumx-react/src/components/dialog/Dialog.tsx
  packages/lumx-react/src/components/notification/Notification.test.tsx
  packages/lumx-react/src/components/notification/Notification.tsx
  packages/lumx-react/src/components/notification/Notifications.stories.tsx
  packages/lumx-react/src/components/notification/__snapshots__/Notification.test.tsx.snap
  packages/lumx-react/src/components/notification/constants.ts
  packages/lumx-react/src/constants.ts
  packages/lumx-react/src/hooks/index.tsx
  packages/lumx-react/src/hooks/useDelayedVisibility.tsx
  packages/site-demo/content/product/components/notification/react/default.tsx
Labels: need: test

#336 feat(link): add React version of Link component
  CHANGELOG.md
  packages/lumx-react/src/components/link/Link.stories.tsx
  packages/lumx-react/src/components/link/Link.test.tsx
  packages/lumx-react/src/components/link/Link.tsx
  packages/lumx-react/src/components/link/__snapshots__/Link.test.tsx.snap
  packages/lumx-react/src/index.ts
Labels: need: test

#331 feat(web-bookmark): add WebBookmark React component
  CHANGELOG.md
  packages/lumx-core/src/scss/components/message/lumapps/_index.scss
  packages/lumx-core/src/scss/components/web-bookmark/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-react/package.json
  packages/lumx-react/src/components/web-bookmark/WebBookmark.stories.tsx
  packages/lumx-react/src/components/web-bookmark/WebBookmark.test.tsx
  packages/lumx-react/src/components/web-bookmark/WebBookmark.tsx
  packages/lumx-react/src/components/web-bookmark/__snapshots__/WebBookmark.test.tsx.snap
  packages/lumx-react/src/index.ts
Labels: need: review-frontend, need: review-integration

#337 feat(select): allow on Blur
  CHANGELOG.md
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/select/Select.stories.tsx
  packages/lumx-react/src/components/select/Select.test.tsx
  packages/lumx-react/src/components/select/Select.tsx
  packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
  packages/lumx-react/src/index.ts
Labels: need: dev-frontend

#340 Feat/mosaic
  CHANGELOG.md
  packages/lumx-core/src/scss/components/mosaic/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-react/src/components/index.ts
  packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.test.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.tsx
  packages/lumx-react/src/components/mosaic/__snapshots__/Mosaic.test.tsx.snap
  packages/lumx-react/src/index.ts
Labels: need: dev-frontend, need: review-frontend

#342 feat(web-bookmark): add size prop
  CHANGELOG.md
  packages/lumx-core/src/scss/components/web-bookmark/lumapps/_index.scss
  packages/lumx-react/src/components/web-bookmark/WebBookmark.stories.tsx
  packages/lumx-react/src/components/web-bookmark/WebBookmark.tsx
  packages/lumx-react/src/components/web-bookmark/__snapshots__/WebBookmark.test.tsx.snap
Labels: need: merge
