Repository lumapps/design-system, pull requests merged in 2020-08, with the labels that each got.

#454 fix(dropdown): fix focus and shrink
  CHANGELOG.md
  packages/lumx-react/src/components/dropdown/Dropdown.stories.tsx
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/components/popover/Popover.tsx
  packages/lumx-react/src/hooks/useFocus.tsx
  packages/lumx-react/src/hooks/useInfiniteScroll.tsx
Labels: need: test

#453 fix(tooltip): make tooltip work on disabled anchor
  CHANGELOG.md
  packages/lumx-core/src/scss/components/tooltip/lumapps/_index.scss
  packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx
  packages/lumx-react/src/components/tooltip/Tooltip.test.tsx
  packages/lumx-react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Labels: need: review-frontend

#455 chore(release): release v0.25.7
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#458 chore: update test dependencies and fix minor errors
  package.json
  packages/lumx-react/package.json
  packages/lumx-react/src/components/chip/Chip.test.tsx
  packages/lumx-react/src/components/chip/__snapshots__/Chip.test.tsx.snap
  packages/lumx-react/src/components/date-picker/DatePickerField.test.tsx
  packages/lumx-react/src/components/dialog/Dialog.stories.tsx
  packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
  yarn.lock
Labels: need: review-frontend

#461 chore: update jest related dependencies
  packages/lumx-react/package.json
  yarn.lock
Labels: need: review-frontend

#462 chore: update webpack and typescript related dependencies
  package.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-react/package.json
  packages/site-demo/content/product/components/dialog/react/sizes.tsx
  packages/site-demo/package.json
  yarn.lock
Labels: need: review-frontend

#463 Tooltip a11y - display the tooltip on focus
  CHANGELOG.md
  packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
Labels: need: review-frontend

#448 docs(table): add table properties to demo
  packages/site-demo/content/product/components/slider/index.mdx
  packages/site-demo/content/product/components/table/index.mdx
Labels: need: merge, need: rebase

#464 feat(dropdown): add fitWithinViewportHeight prop
  CHANGELOG.md
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
Labels: need: review-frontend

#467 chore(release): release v0.25.9
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#468 fix(date-picker-field): use locale prop on input
  CHANGELOG.md
  packages/lumx-react/src/components/date-picker/DatePickerField.tsx
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
Labels: need: review-frontend

#441 feat(side-navigation): item actions
  CHANGELOG.md
  packages/lumx-core/src/scss/components/side-navigation/lumapps/_index.scss
  packages/lumx-core/src/scss/components/side-navigation/lumapps/_mixins.scss
  packages/lumx-react/src/components/side-navigation/SideNavigation.stories.tsx
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
  packages/lumx-react/src/components/side-navigation/__snapshots__/SideNavigationItem.test.tsx.snap
Labels: need: review-frontend

#470 release/0.25.11
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#473 fix(text-field): pass type prop to input
  CHANGELOG.md
  packages/lumx-core/src/scss/components/text-field/lumapps/_mixins.scss
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: review-frontend
