Repository lumapps/design-system, pull requests merged in 2020-05, with the labels that each got.

#384 Add custom default month for date picker
  CHANGELOG.md
  packages/lumx-core/src/js/date-picker.ts
  packages/lumx-react/src/components/date-picker/DatePicker.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.tsx
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePicker.test.tsx.snap
Labels: need: test

#393 Minor cleaning: move stories
  packages/lumx-react/src/components/chip/Chip.stories.tsx
  packages/lumx-react/src/components/select/SelectMultiple.stories.tsx
Labels: need: merge

#391 feat(thumbnail): Img props
  CHANGELOG.md
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
Labels: need: review-frontend

#394 feat(link-preview): added isThumbnailCrossOriginEnabled prop
  CHANGELOG.md
  packages/lumx-react/src/components/link-preview/LinkPreview.tsx
Labels: need: review-frontend

#392 fix(textfield): put chips after icon
  packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: test

#398 fix(mosaic): fix thumbnails showing as clickable
  CHANGELOG.md
  packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.test.tsx
  packages/lumx-react/src/components/mosaic/Mosaic.tsx
  packages/lumx-react/src/components/mosaic/__snapshots__/Mosaic.test.tsx.snap
Labels: need: review-frontend

#399 fix Interface typo onInfinite to onInfiniteScroll for Autocomplete and Dropdown
  CHANGELOG.md
  packages/lumx-react/src/components/autocomplete/Autocomplete.tsx
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
Labels: need: review-frontend

#401 fix(text-field): fix clear button type
  CHANGELOG.md
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: review-frontend
