Repository lumapps/design-system, pull requests merged in 2020-06, with the labels that each got.

#403 Fix/LUM-9878 Textarea nb rows
  CHANGELOG.md
  packages/lumx-react/src/components/text-field/TextField.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: review-frontend

#387 DatePicker and DPField accept a Date object
  CHANGELOG.md
  packages/lumx-react/src/components/date-picker/DatePicker.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.test.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.tsx
  packages/lumx-react/src/components/date-picker/DatePickerValueProp.ts
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
Labels: need: test

#404 fix(textfield): check computation result
  packages/lumx-react/src/components/text-field/TextField.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: test

#409 fix nested click away
  CHANGELOG.md
  packages/lumx-react/src/components/date-picker/DatePickerField.tsx
  packages/lumx-react/src/components/dialog/Dialog.stories.tsx
  packages/lumx-react/src/components/dialog/Dialog.tsx
  packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/hooks/useClickAway.tsx
  packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.stories.tsx
  packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx
  packages/lumx-react/src/utils/ClickAwayProvider/index.ts
  packages/lumx-react/src/utils/type.ts
Labels: need: test

#410 fix(select): fix arrow icon on empty selection
  CHANGELOG.md
  packages/lumx-react/src/components/select/Select.tsx
Labels: bug, need: test

#416 fix(storybook): fix lumapps/material theme switcher
  packages/lumx-react/.storybook/story-block/useInjectTheme.ts
Labels: need: review-frontend

#418 fix: create custom SCSS format to fix grey icon style on material
  CHANGELOG.md
  packages/lumx-core/src/scss/core/generated/lumapps/_variables.scss
  packages/lumx-core/src/scss/core/generated/material/_variables.scss
  packages/lumx-core/style-dictionary/config/gen-scss-variables.js
  packages/lumx-core/style-dictionary/config/gen-ts-variables.js
  packages/lumx-core/style-dictionary/config/utils/_genHeader.js
Labels: need: review-frontend

#421 fix(link-preview): fix thumbnailProps typing
  CHANGELOG.md
  packages/lumx-react/src/components/link-preview/LinkPreview.tsx
Labels: need: review-frontend

#415 fix(chip): fix click propagation on after/before
  CHANGELOG.md
  packages/lumx-react/src/components/chip/Chip.stories.tsx
  packages/lumx-react/src/components/chip/Chip.test.tsx
  packages/lumx-react/src/components/chip/Chip.tsx
Labels: bug, need: test

#417 Feat - List-item-link: create an <a> if an href prop is provided
  CHANGELOG.md
  packages/lumx-angularjs/src/components/list/list-item.html
  packages/lumx-angularjs/src/components/list/list-item_directive.js
  packages/lumx-angularjs/src/components/list/list_directive.js
  packages/lumx-core/src/scss/components/list/lumapps/_index.scss
  packages/lumx-core/src/scss/components/list/lumapps/_mixins.scss
  packages/lumx-react/src/components/list/List.stories.tsx
  packages/lumx-react/src/components/list/List.tsx
  packages/lumx-react/src/components/list/ListItem.tsx
Labels: need: test

#425 chore: fix CHANGELOG
  CHANGELOG.md
Labels: need: review-frontend

#427 Feat/remove required angularjs
  CHANGELOG.md
  packages/lumx-angularjs/src/components/select/select.html
  packages/lumx-angularjs/src/components/text-field/text-field.html
Labels: need: review-frontend

#424 FIX/LUM-10327: Date picker weeks display
  CHANGELOG.md
  packages/lumx-core/src/js/date-picker.ts
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerControlled.test.tsx.snap
Labels: need: merge, need: test

#430 chore(release): release v0.25.0
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#431 feat(tooltip): handle multiline and empty cases
  CHANGELOG.md
  packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
Labels: need: test
