Repository lumapps/design-system, pull requests merged in 2020-03, with the labels that each got.

#345 Add ReactNode as an allowed type for SideNavigationItem
  CHANGELOG.md
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
Labels: need: merge

#353 fix(link): fix component types
  CHANGELOG.md
  packages/lumx-react/src/components/link/Link.tsx
Labels: need: review-frontend

#346 Add ReactNode as allowed type to Tab label
  CHANGELOG.md
  packages/lumx-react/src/components/tabs/Tab.tsx
Labels: need: merge, need: rebase

#341 feat(flex-box): add react component
  CHANGELOG.md
  packages/lumx-core/src/scss/components/flex-box/lumapps/_index.scss
  packages/lumx-core/src/scss/lumx-theme-lumapps.scss
  packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx
  packages/lumx-react/src/components/flex-box/FlexBox.test.tsx
  packages/lumx-react/src/components/flex-box/FlexBox.tsx
  packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
  packages/lumx-react/src/index.ts
  packages/lumx-react/src/testing/utils.ts
Labels: need: review-frontend

#355 Pass badge to avatar and user block and fix list item padding
  CHANGELOG.md
  packages/lumx-angularjs/src/components/list/list_directive.js
  packages/lumx-react/src/components/avatar/Avatar.stories.tsx
  packages/lumx-react/src/components/avatar/Avatar.test.tsx
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
  packages/lumx-react/src/components/badge/Badge.stories.tsx
  packages/lumx-react/src/components/badge/Badge.test.tsx
  packages/lumx-react/src/components/badge/Badge.tsx
  packages/lumx-react/src/components/list/List.stories.tsx
  packages/lumx-react/src/components/list/List.tsx
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.test.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
  packages/lumx-react/src/index.ts
  packages/site-demo/content/product/components/post-block/react/default.tsx
  packages/site-demo/content/product/components/user-block/react/extended.tsx
  packages/site-demo/content/product/components/user-block/react/size-l.tsx
  packages/site-demo/content/product/components/user-block/react/size-m.tsx
  packages/site-demo/content/product/components/user-block/react/size-s.tsx
  packages/site-demo/content/product/components/user-block/react/vertical.tsx
Labels: need: test

#356 chore: replace grid by flexbox
  packages/lumx-react/src/components/dialog/Dialog.stories.tsx
  packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
  packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx
  packages/lumx-react/src/components/flex-box/FlexBox.tsx
  packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
  packages/lumx-react/src/components/icon/Icon.stories.tsx
  packages/site-demo/content/product/components/expansion-panel/react/examples.tsx
  packages/site-demo/content/product/components/image-block/react/default.tsx
  packages/site-demo/content/product/components/popover/react/positions.tsx
  packages/site-demo/content/product/components/post-block/react/default.tsx
  packages/site-demo/content/product/components/toolbar/react/back.tsx
  packages/site-demo/content/product/components/toolbar/react/media-picker.tsx
  packages/site-demo/content/product/foundations/iconography/index.mdx
  packages/site-demo/src/layout/Main.tsx
Labels: need: dev-frontend

#357 chore(release): release v0.21.10
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#358 chore(react): publish source files on NPM
  CHANGELOG.md
  packages/lumx-react/webpack.config.js
Labels: need: review-frontend

#362 chore(release): release v0.21.12
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#365 feat(thumbnail): add props to manage cors and listen window's resizing
  CHANGELOG.md
  packages/lumx-react/src/components/thumbnail/FocusedImage.ts
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/components/thumbnail/useFocusedImage.tsx
  packages/lumx-react/src/index.ts
Labels: need: review-doc, need: review-frontend, need: test

#366 chore(release): release v0.21.14
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend
