Repository lumapps/design-system, pull requests merged in 2021-02, with the labels that each got.

#607 docs(spacing): added foundation/spacing doc
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/foundations/spacing/assets/spacing-applied.png
  packages/site-demo/content/product/foundations/spacing/index.mdx
Labels: need: review-doc

#608 docs(typography): updated doc
  packages/site-demo/content/product/foundations/typography/index.mdx
Labels: need: review-doc

#609 docs(flexbox): added light doc
  packages/site-demo/content/product/components/flex-box/index.mdx
  packages/site-demo/content/product/components/flex-box/react/.gitkeep
Labels: need: review-doc

#616 fix(tooltip): fix closing on covered anchor
  CHANGELOG.md
  packages/lumx-react/src/components/table/__snapshots__/Table.test.tsx.snap
  packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx
  packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
Labels: need: merge

#614 chore(demo): Handle prefix-based routing
  .docker/nginx.conf
Labels: need: merge

#622 fix/thumbnail background style
  CHANGELOG.md
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
  packages/lumx-react/src/components/alert-dialog/__snapshots__/AlertDialog.test.tsx.snap
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
  packages/lumx-react/src/components/comment-block/__snapshots__/CommentBlock.test.tsx.snap
  packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
  packages/lumx-react/src/components/image-block/__snapshots__/ImageBlock.test.tsx.snap
  packages/lumx-react/src/components/lightbox/__snapshots__/Lightbox.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/ListDivider.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/ListItem.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/ListSubheader.test.tsx.snap
  packages/lumx-react/src/components/popover/__snapshots__/Popover.test.tsx.snap
  packages/lumx-react/src/components/post-block/__snapshots__/PostBlock.test.tsx.snap
  packages/lumx-react/src/components/progress/__snapshots__/Progress.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonCircle.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonRectangle.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonTypography.test.tsx.snap
  packages/lumx-react/src/components/slider/__snapshots__/Slider.test.tsx.snap
  packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
  packages/lumx-react/src/components/table/__snapshots__/Table.test.tsx.snap
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
  packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
  packages/lumx-react/src/testing/utils/itShouldRenderStories.tsx
Labels: need: review-frontend

#628 release/v1.0.8
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/lumx-react/src/components/badge/Badge.stories.tsx
  packages/lumx-react/src/components/index.ts
  packages/lumx-react/src/components/skeleton/SkeletonCircle.tsx
  packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx
  packages/lumx-react/src/components/skeleton/SkeletonTypography.tsx
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonCircle.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonRectangle.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonTypography.test.tsx.snap
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
  packages/lumx-react/src/components/thumbnail/useFocusPoint.ts
  packages/lumx-react/src/stories/knobs/sizeKnob.ts
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#630 fix(tabs): remove default props preventing onChange from being called
  CHANGELOG.md
  packages/lumx-react/src/components/progress-tracker/ProgressTracker.stories.tsx
  packages/lumx-react/src/components/progress-tracker/ProgressTrackerProvider.tsx
  packages/lumx-react/src/components/tabs/TabProvider.tsx
  packages/lumx-react/src/components/tabs/Tabs.stories.tsx
Labels: need: review-frontend

#631 fix(link): fix default style in button mode
  CHANGELOG.md
  packages/lumx-core/src/scss/components/link/_mixins.scss
  packages/lumx-react/src/components/link/Link.stories.tsx
Labels: need: review-frontend

#629 Feat/Flag component
  CHANGELOG.md
  packages/lumx-core/src/scss/components/flag/_index.scss
  packages/lumx-core/src/scss/lumx.scss
  packages/lumx-react/src/components/flag/Flag.stories.tsx
  packages/lumx-react/src/components/flag/Flag.test.tsx
  packages/lumx-react/src/components/flag/Flag.tsx
  packages/lumx-react/src/components/flag/__snapshots__/Flag.test.tsx.snap
  packages/lumx-react/src/components/flag/index.ts
  packages/lumx-react/src/index.ts
Labels: need: review-frontend, need: review-integration

#633 feat(color): use css variable for primary color
  packages/lumx-core/src/css/material.css
  packages/lumx-core/src/scss/core/color/_functions.scss
Labels: need: review-frontend

#636 fix(table-row): move tabIndex above forward props spread
  CHANGELOG.md
  packages/lumx-react/src/components/checkbox/Checkbox.test.tsx
  packages/lumx-react/src/components/checkbox/Checkbox.tsx
  packages/lumx-react/src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/lumx-react/src/components/radio-button/RadioButton.test.tsx
  packages/lumx-react/src/components/radio-button/RadioButton.tsx
  packages/lumx-react/src/components/radio-button/__snapshots__/RadioButton.test.tsx.snap
  packages/lumx-react/src/components/table/TableRow.tsx
Labels: need: merge

#642 fix(avatar): move circle shape to thumbnail wrapper
  packages/lumx-core/src/scss/components/avatar/_index.scss
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
Labels: need: review-frontend

#641 feat(popover): add boundaryRef prop to change overflow boundary
  CHANGELOG.md
  packages/lumx-react/src/components/popover/Popover.stories.tsx
  packages/lumx-react/src/components/popover/Popover.tsx
Labels: need: merge

#643 chore(release): release v1.0.11
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: merge
