Repository lumapps/design-system, pull requests merged in 2021-05, with the labels that each got.

#668 Merge v1.0.16 into master
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/lumx-react/src/components/slideshow/useKeyOrSwipeNavigate.ts
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#649 docs(form-validation): added doc page and content
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/patterns/form-validation/assets/error-message.png
  packages/site-demo/content/product/patterns/form-validation/assets/error-state.png
  packages/site-demo/content/product/patterns/form-validation/assets/helpers.png
  packages/site-demo/content/product/patterns/form-validation/assets/inline-validation.png
  packages/site-demo/content/product/patterns/form-validation/assets/optional-mandatory.png
  packages/site-demo/content/product/patterns/form-validation/assets/stepper-behavior1.png
  packages/site-demo/content/product/patterns/form-validation/assets/stepper-behavior2.png
  packages/site-demo/content/product/patterns/form-validation/assets/stepper-behavior3.png
  packages/site-demo/content/product/patterns/form-validation/assets/submit-behavior1.png
  packages/site-demo/content/product/patterns/form-validation/assets/submit-behavior2.png
  packages/site-demo/content/product/patterns/form-validation/assets/submit-error.png
  packages/site-demo/content/product/patterns/form-validation/assets/success-state.png
  packages/site-demo/content/product/patterns/form-validation/assets/validation1.png
  packages/site-demo/content/product/patterns/form-validation/assets/validation2.png
  packages/site-demo/content/product/patterns/form-validation/assets/warning-state.png
  packages/site-demo/content/product/patterns/form-validation/index.mdx
Labels: need: review-doc

#655 docs(pick-and-manage): filled doc texts and images
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/patterns/pick-and-manage/assets/autocomplete.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/empty-state.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/empty-state2.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/expandable-item.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/multi-selection.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/overview.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/remove.png
  packages/site-demo/content/product/patterns/pick-and-manage/assets/single-selection.png
  packages/site-demo/content/product/patterns/pick-and-manage/index.mdx
Labels: need: review-doc

#656 docs(drag-and-drop): added page, entry nav and content
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/patterns/drag-and-drop/assets/drag-and-drop-behavior1.png
  packages/site-demo/content/product/patterns/drag-and-drop/assets/drag-and-drop-behavior2.png
  packages/site-demo/content/product/patterns/drag-and-drop/assets/dropzone-behavior1.png
  packages/site-demo/content/product/patterns/drag-and-drop/assets/dropzone-behavior2.png
  packages/site-demo/content/product/patterns/drag-and-drop/index.mdx
Labels: need: review-doc

#657 docs(widget-settings): added new page and nav entry
  packages/site-demo/content/menu.yml
  packages/site-demo/content/product/patterns/widgets-settings/assets/anatomy.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/default-behavior.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/full-view.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/heading-spacing-example.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/heading-spacing.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/main-sub-settings.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/switch-checkboxe.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-advanced.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-advanced1x.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-body.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-body1x.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-footer.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-footer1x.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-header.png
  packages/site-demo/content/product/patterns/widgets-settings/assets/widget-header1x.png
  packages/site-demo/content/product/patterns/widgets-settings/index.mdx
Labels: need: review-doc

#669 fix(slideshow): fix touch swipe event handling
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-core/src/js/utils.ts
  packages/lumx-icons/package.json
  packages/lumx-react/.storybook/story-block/StoryBlock.tsx
  packages/lumx-react/.storybook/story-block/decorator.jsx
  packages/lumx-react/package.json
  packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
  packages/lumx-react/src/components/comment-block/__snapshots__/CommentBlock.test.tsx.snap
  packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.test.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.tsx
  packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
  packages/lumx-react/src/components/slideshow/useKeyNavigate.ts
  packages/lumx-react/src/components/slideshow/useKeyOrSwipeNavigate.ts
  packages/lumx-react/src/components/slideshow/useSwipeNavigate.ts
  packages/site-demo/content/product/components/date-picker/react/default.tsx
  packages/site-demo/content/product/components/date-picker/react/input.tsx
  packages/site-demo/content/product/components/date-picker/react/restricted.tsx
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend, need: test
