Repository lumapps/design-system, pull requests merged in 2021-12, with the labels that each got.

#739 release/v2.1.5
  .github/workflows/chromatic.yaml
  .github/workflows/github-actions-validator.yml
  CHANGELOG.md
  lerna.json
  package.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#740 fix(release): fix TS types generation, version and changelog update
  .github/workflows/chromatic.yaml
  CHANGELOG.md
  README.md
  package.json
  packages/lumx-core/package.json
  packages/lumx-react/package.json
  yarn.lock
Labels: need: review-frontend

#741 fix(lightbox): fix wrong focus parent behavior
  CHANGELOG.md
  packages/lumx-react/src/components/lightbox/Lightbox.stories.tsx
  packages/lumx-react/src/components/lightbox/Lightbox.tsx
Labels: need: merge

#742 release/2.1.6
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#743 fix(textfield): show maxlength counter when there is no label
  CHANGELOG.md
  packages/lumx-core/src/scss/components/text-field/_index.scss
  packages/lumx-react/src/components/text-field/TextField.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: review-frontend, need: review-integration

#744 Fix/userblock-linkas
  CHANGELOG.md
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
Labels: need: merge

#749 Revert: thumbnail, avatar, userblock improved link a11y
  CHANGELOG.md
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
  packages/lumx-core/src/scss/components/user-block/_index.scss
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
Labels: need: review-frontend

#748 Chore/fixed soften buttons
  CHANGELOG.md
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/src/scss/components/chip/_index.scss
  packages/lumx-core/src/scss/components/flag/_index.scss
  packages/lumx-core/src/scss/components/icon/_mixins.scss
  packages/lumx-core/src/scss/components/list/_mixins.scss
  packages/lumx-core/src/scss/components/side-navigation/_mixins.scss
  packages/lumx-core/src/scss/components/thumbnail/_variables.scss
  packages/lumx-core/src/scss/components/uploader/_index.scss
  packages/lumx-core/src/scss/core/state/_mixins.scss
  packages/lumx-core/style-dictionary/properties/components/button.json
  packages/lumx-core/style-dictionary/properties/components/navigation.json
  packages/lumx-core/style-dictionary/properties/components/tabs.json
  packages/lumx-core/style-dictionary/properties/core/color.json
  packages/lumx-react/src/components/drag-handle/DragHandle.tsx
  packages/lumx-react/src/components/flag/Flag.test.tsx
  packages/lumx-react/src/components/flag/Flag.tsx
  packages/lumx-react/src/components/flag/__snapshots__/Flag.test.tsx.snap
  packages/lumx-react/src/components/icon/Icon.tsx
  packages/lumx-react/src/components/message/Message.tsx
  packages/site-demo/content/product/components/chip/react/default.tsx
  packages/site-demo/content/product/components/chip/react/dismissible.tsx
  packages/site-demo/content/product/components/chip/react/filter.tsx
  packages/site-demo/content/product/components/chip/react/small.tsx
Labels: need: merge

#750 chore(design-tokens): add value to TS generated tokens
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/style-dictionary/config/gen-css-variables.js
  packages/lumx-core/style-dictionary/config/gen-ts-variables.js
Labels: need: merge
