Repository lumapps/design-system, pull requests merged in 2021-04, with the labels that each got.

#658 fix(thumbnail): limit resize update
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/lumx-react/src/hooks/useOnResize.ts
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: DO-NOT-MERGE

#660 fix(core): fix specificity of css selector for links
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-core/src/scss/components/link/_index.scss
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: merge

#662 feat(icon-button): add showTooltip prop
  CHANGELOG.md
  packages/lumx-react/src/components/button/IconButton.tsx
Labels: need: review-frontend
