Repository lumapps/design-system, pull requests merged in 2021-11, with the labels that each got.

#710 chore(release): release v2.1.1
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#714 fix(icon-button): simplify typing
  CHANGELOG.md
  packages/lumx-react/src/components/button/IconButton.test.tsx
  packages/lumx-react/src/components/button/IconButton.tsx
  packages/lumx-react/src/components/button/__snapshots__/IconButton.test.tsx.snap
Labels: need: review-frontend

#720 feat(text-field): add `afterElement` prop
  CHANGELOG.md
  packages/lumx-core/src/scss/components/text-field/_index.scss
  packages/lumx-core/src/scss/components/text-field/_mixins.scss
  packages/lumx-react/src/components/avatar/Avatar.stories.tsx
  packages/lumx-react/src/components/button/Button.stories.tsx
  packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
  packages/lumx-react/src/components/dialog/Dialog.stories.tsx
  packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
  packages/lumx-react/src/components/link-preview/LinkPreview.stories.tsx
  packages/lumx-react/src/components/skeleton/SkeletonRectangle.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/stories/knobs/buttonKnob.ts
  packages/lumx-react/src/stories/knobs/emphasisKnob.ts
  packages/lumx-react/src/stories/knobs/index.ts
Labels: need: review-frontend

#721 release/2.1.2
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/README.md
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/README.md
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
Labels: need: review-frontend

#723 Add a material theme switcher on demo site and storybook
  packages/lumx-react/.storybook/story-block/StoryBlock.tsx
  packages/lumx-react/.storybook/story-block/index.scss
  packages/lumx-react/.storybook/story-block/styles.js
  packages/lumx-react/src/utils/MaterialThemeSwitcher/MaterialThemeSwitcher.tsx
  packages/lumx-react/src/utils/MaterialThemeSwitcher/index.ts
  packages/site-demo/content/product/components/date-picker/react/default.tsx
  packages/site-demo/content/product/components/date-picker/react/input.tsx
  packages/site-demo/content/product/components/date-picker/react/restricted.tsx
  packages/site-demo/src/components/layout/Main.tsx
  packages/site-demo/src/style/index.scss
  packages/site-demo/src/style/layout/main/_main.scss
Labels: need: review-frontend, DO-NOT-MERGE

#730 fix(slideshow): fix keyboard navigation
  CHANGELOG.md
  packages/lumx-react/src/components/slideshow/useKeyNavigate.ts
Labels: need: review-frontend

#729 feat: soften medium and low dark buttons color
  CHANGELOG.md
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/src/scss/components/flag/_index.scss
  packages/lumx-core/src/scss/components/list/_mixins.scss
  packages/lumx-core/src/scss/components/side-navigation/_mixins.scss
  packages/lumx-core/src/scss/components/thumbnail/_variables.scss
  packages/lumx-core/src/scss/components/uploader/_index.scss
  packages/lumx-core/src/scss/core/state/_mixins.scss
  packages/lumx-core/style-dictionary/properties/components/button.json
  packages/lumx-core/style-dictionary/properties/components/navigation.json
  packages/lumx-core/style-dictionary/properties/components/tabs.json
  packages/lumx-core/style-dictionary/properties/core/color.json
  packages/lumx-react/src/components/flag/Flag.test.tsx
  packages/lumx-react/src/components/flag/Flag.tsx
  packages/lumx-react/src/components/flag/__snapshots__/Flag.test.tsx.snap
  packages/lumx-react/src/components/message/Message.tsx
Labels: need: review-frontend, need: review-integration

#734 fix(dialog): focus parent on dialog close
  CHANGELOG.md
  packages/lumx-react/src/components/dialog/Dialog.stories.tsx
  packages/lumx-react/src/components/dialog/Dialog.tsx
  packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
Labels: need: review-frontend

#731 fix git hooks
  .husky/commit-msg
  README.md
  package.json
Labels: need: review-frontend

#735 chore(release): release v2.1.4
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#737 fix(style-dictionnary): fix calls for prettier scripts
  packages/lumx-core/style-dictionary/config/gen-css-variables.js
  packages/lumx-core/style-dictionary/config/gen-scss-variables.js
  packages/lumx-core/style-dictionary/config/gen-ts-variables.js
  packages/lumx-core/style-dictionary/config/utils/_prettier-scss.js
  packages/lumx-core/style-dictionary/config/utils/_prettier-ts.js
Labels: need: review-frontend

#736 [a11y] Add linkProps to Thumbnail/Avatar/UserBlock
  CHANGELOG.md
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
  packages/lumx-core/src/scss/components/user-block/_index.scss
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
Labels: need: review-frontend, need: review-integration

#738 chore(color): limit soft dark to wanted components
  CHANGELOG.md
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/src/scss/components/chip/_index.scss
  packages/lumx-core/src/scss/components/icon/_mixins.scss
  packages/lumx-core/src/scss/core/state/_mixins.scss
  packages/lumx-core/style-dictionary/properties/components/navigation.json
  packages/lumx-react/src/components/drag-handle/DragHandle.tsx
Labels: need: review-frontend, need: review-integration
