Repository lumapps/design-system, pull requests merged in 2021-01, with the labels that each got.

#587 refactor(comment-block): add variant and remove useless props LUM-13511
  CHANGELOG.md
  packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
  packages/lumx-react/src/components/comment-block/CommentBlock.tsx
  packages/lumx-react/src/components/progress/Progress.tsx
  packages/lumx-react/src/components/select/constants.ts
  packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx
  packages/lumx-react/src/components/table/TableCell.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/components/uploader/Uploader.tsx
  packages/site-demo/content/product/components/comment-block/react/default.tsx
  packages/site-demo/content/product/components/comment-block/react/relevant.tsx
  packages/site-demo/content/product/components/comment-block/react/threaded.tsx
Labels: need: test

#517 chore: upgrade to mdi 5.8.55 and handle backward compatibility LUM-12974
  CHANGELOG.md
  packages/lumx-icons/README-v4-to-v5-migration.md
  packages/lumx-icons/font.scss
  packages/lumx-icons/index.d.ts
  packages/lumx-icons/index.js
  packages/lumx-icons/package.json
  packages/lumx-icons/v4-to-v5-aliases.d.ts
  packages/lumx-icons/v4-to-v5-aliases.js
  packages/lumx-icons/v4-to-v5-aliases.scss
  packages/site-demo/content/product/components/uploader/react/default.tsx
  yarn.lock
Labels: need: merge

#590 refactor(avatar): use thumbnail inside avatar LUM-11237
  CHANGELOG.md
  packages/lumx-core/src/scss/components/avatar/_index.scss
  packages/lumx-react/src/components/avatar/Avatar.stories.tsx
  packages/lumx-react/src/components/avatar/Avatar.test.tsx
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
  packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
  packages/lumx-react/src/components/comment-block/CommentBlock.tsx
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
  packages/site-demo/content/product/components/avatar/react/actions.tsx
  packages/site-demo/content/product/components/avatar/react/default.tsx
  packages/site-demo/content/product/components/badge/react/icon.tsx
  packages/site-demo/content/product/components/badge/react/label.tsx
  packages/site-demo/content/product/components/comment-block/react/default.tsx
  packages/site-demo/content/product/components/comment-block/react/relevant.tsx
  packages/site-demo/content/product/components/comment-block/react/threaded.tsx
  packages/site-demo/content/product/components/list/react/big.tsx
  packages/site-demo/content/product/components/list/react/huge.tsx
  packages/site-demo/content/product/components/list/react/regular.tsx
  packages/site-demo/content/product/components/list/react/tiny.tsx
  packages/site-demo/content/product/components/post-block/react/default.tsx
  packages/site-demo/content/product/components/user-block/react/extended.tsx
  packages/site-demo/content/product/components/user-block/react/size-l.tsx
  packages/site-demo/content/product/components/user-block/react/size-m.tsx
  packages/site-demo/content/product/components/user-block/react/size-s.tsx
  packages/site-demo/content/product/components/user-block/react/vertical.tsx
Labels: need: test

#589 chore(icons): fix v4 to v5 icon aliases
  packages/lumx-icons/v4-to-v5-aliases.d.ts
  packages/lumx-icons/v4-to-v5-aliases.js
  packages/lumx-icons/v4-to-v5-aliases.scss
Labels: need: review-frontend

#588 fix/slideshow group by
  packages/lumx-react/src/components/avatar/Avatar.test.tsx
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
  packages/lumx-react/src/components/flex-box/FlexBox.test.tsx
  packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
  packages/lumx-react/src/components/list/List.test.tsx
  packages/lumx-react/src/components/list/ListDivider.test.tsx
  packages/lumx-react/src/components/list/ListItem.test.tsx
  packages/lumx-react/src/components/list/ListSubheader.test.tsx
  packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/ListDivider.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/ListItem.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/ListSubheader.test.tsx.snap
  packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.test.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.tsx
  packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
  packages/lumx-react/src/components/slideshow/useKeyOrSwipeNavigate.ts
  packages/lumx-react/src/components/slideshow/usePaginationVisibleRange.ts
  packages/lumx-react/src/components/user-block/UserBlock.test.tsx
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
  packages/lumx-react/src/hooks/useInterval.tsx
  packages/lumx-react/src/testing/utils/commonTestsSuite.ts
  packages/lumx-react/src/testing/utils/index.ts
  packages/lumx-react/src/testing/utils/itShouldRenderStories.tsx
Labels: need: review-frontend

#601 fix(switch): fix content position on right alignment
  CHANGELOG.md
  packages/lumx-core/src/scss/components/switch/_index.scss
  packages/lumx-react/src/components/switch/Switch.stories.tsx
Labels: need: review-frontend

#602 feat(popover): add usePortal prop to skip portal in some case
  CHANGELOG.md
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/components/popover/Popover.stories.tsx
  packages/lumx-react/src/components/popover/Popover.tsx
Labels: need: review-frontend

#615 Feat/lum 13946 alert dialog
  CHANGELOG.md
  packages/lumx-react/src/components/alert-dialog/AlertDialog.stories.tsx
  packages/lumx-react/src/components/alert-dialog/AlertDialog.test.tsx
  packages/lumx-react/src/components/alert-dialog/AlertDialog.tsx
  packages/lumx-react/src/components/alert-dialog/__snapshots__/AlertDialog.test.tsx.snap
  packages/lumx-react/src/components/alert-dialog/index.ts
  packages/lumx-react/src/components/dialog/Dialog.tsx
  packages/lumx-react/src/components/notification/Notification.tsx
  packages/lumx-react/src/components/notification/__snapshots__/Notification.test.tsx.snap
Labels: need: merge
