Repository lumapps/design-system, pull requests merged in 2022-06, with the labels that each got.

#837 chore(demo-site): minor fixes and improvements
  packages/site-demo/content/product/components/badge/index.mdx
  packages/site-demo/content/product/components/button/index.mdx
  packages/site-demo/content/product/components/chip/index.mdx
  packages/site-demo/content/product/components/lightbox/index.mdx
  packages/site-demo/content/product/components/list/index.mdx
  packages/site-demo/content/product/components/message/index.mdx
  packages/site-demo/content/product/components/mosaic/index.mdx
  packages/site-demo/content/product/components/popover/index.mdx
  packages/site-demo/content/product/components/skeleton/index.mdx
  packages/site-demo/content/product/components/skeleton/react/typography.tsx
  packages/site-demo/content/product/components/slideshow/index.mdx
  packages/site-demo/content/product/components/text-field/index.mdx
  packages/site-demo/content/product/components/thumbnail/index.mdx
  packages/site-demo/content/product/foundations/size/index.mdx
  packages/site-demo/content/product/foundations/typography/index.mdx
  packages/site-demo/content/product/patterns/filter-and-sort/index.mdx
  packages/site-demo/content/product/patterns/form-validation/index.mdx
  packages/site-demo/content/product/patterns/loading-state/index.mdx
  packages/site-demo/content/product/patterns/pick-and-manage/index.mdx
  packages/site-demo/content/product/patterns/translation/index.mdx
  packages/site-demo/content/product/patterns/widgets-settings/index.mdx
  packages/site-demo/content/product/utilities/typography/index.mdx
  packages/site-demo/plugins/utils/cleanExcerpt.js
Labels: need: review-frontend

#838 chore(demo-site): document link accessibility
  packages/site-demo/content/product/components/link/index.mdx
Labels: need: review-frontend

#844 docs(button): document accessibility concerns
  packages/lumx-react/src/components/button/Button.stories.tsx
  packages/lumx-react/src/components/button/ButtonRoot.tsx
  packages/site-demo/content/product/components/button/index.mdx
Labels: need: rebase

#848 Docs/responsive fixes
  packages/lumx-react/src/components/table/__snapshots__/Table.test.tsx.snap
  packages/site-demo/content/product/components/popover/index.mdx
  packages/site-demo/content/product/components/popover/react/alignments.tsx
  packages/site-demo/content/product/components/popover/react/positions.tsx
  packages/site-demo/content/product/components/skeleton/react/typography.tsx
  packages/site-demo/content/product/components/table/react/default.tsx
  packages/site-demo/content/product/components/tabs/react/default.tsx
  packages/site-demo/content/product/components/tabs/react/icon-tabs.tsx
  packages/site-demo/content/product/components/tabs/react/left-tabs.tsx
  packages/site-demo/content/product/foundations/size/index.mdx
  packages/site-demo/content/product/patterns/translation/index.mdx
  packages/site-demo/content/product/patterns/widgets-settings/index.mdx
  packages/site-demo/src/components/content/DemoBlock/DemoBlock.tsx
  packages/site-demo/src/components/layout/MainContent/MainContent.scss
Labels: need: merge
