Repository lumapps/design-system, pull requests merged in 2022-10, with the labels that each got.

#880 chore(flexbox): add as prop to cutomize component render
  CHANGELOG.md
  packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx
  packages/lumx-react/src/components/flex-box/FlexBox.tsx
  packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
  packages/lumx-react/src/components/generic-block/GenericBlock.stories.jsx
Labels: need: review-frontend, hacktoberfest-accepted

#887 chore(ci): update checkout github action
  .github/workflows/chromatic.yaml
  .github/workflows/release.yml
  .github/workflows/validate-pull-request.yml
Labels: need: merge, hacktoberfest-accepted

#885 chore(storybook): improve stories `today` param handling
  packages/lumx-react/src/stories/generated/Heading/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Heading/automatic-heading-level.tsx
  packages/lumx-react/storybook/story-block/StoryBlock.tsx
  packages/site-demo/content/product/components/date-picker/react/default.tsx
  packages/site-demo/content/product/components/date-picker/react/input.tsx
  packages/site-demo/content/product/components/date-picker/react/restricted.tsx
Labels: need: merge, hacktoberfest-accepted

#888 feat(text): improve icon alignment and add noWrap prop
  CHANGELOG.md
  packages/lumx-core/src/scss/components/text/_index.scss
  packages/lumx-react/src/components/text/Text.stories.jsx
  packages/lumx-react/src/components/text/Text.test.tsx
  packages/lumx-react/src/components/text/Text.tsx
  packages/lumx-react/src/stories/withResizableBox.tsx
  packages/site-demo/content/product/components/text/index.mdx
  packages/site-demo/plugins/utils/rewriteJSXComponent.spec.js
  packages/site-demo/plugins/utils/rewriteJSXComponents.js
Labels: need: review-frontend, hacktoberfest-accepted

#886 feat(inline-list): create InlineList component
  CHANGELOG.md
  packages/lumx-core/src/scss/components/inline-list/_index.scss
  packages/lumx-core/src/scss/lumx.scss
  packages/lumx-react/src/components/inline-list/InlineList.stories.tsx
  packages/lumx-react/src/components/inline-list/InlineList.test.tsx
  packages/lumx-react/src/components/inline-list/InlineList.tsx
  packages/lumx-react/src/components/inline-list/index.ts
  packages/lumx-react/src/components/text/Text.tsx
  packages/lumx-react/src/index.ts
  packages/lumx-react/src/utils/className.ts
  packages/lumx-react/src/utils/type.ts
  packages/site-demo/content/product/components/inline-list/index.mdx
Labels: need: review-frontend, hacktoberfest-accepted

#881 docs(generic-block): improve documentation
  packages/lumx-react/src/components/generic-block/GenericBlock.tsx
  packages/lumx-react/src/components/generic-block/constants.ts
  packages/lumx-react/src/components/generic-block/index.ts
  packages/lumx-react/src/components/inline-list/index.ts
  packages/lumx-react/src/stories/generated/GenericBlock/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/GenericBlock/default.tsx
  packages/lumx-react/src/stories/generated/GenericBlock/horizontal-alignment.tsx
  packages/lumx-react/src/stories/generated/GenericBlock/sizes.tsx
  packages/lumx-react/src/stories/generated/GenericBlock/vertical-alignment.tsx
  packages/site-demo/content/product/components/generic-block/index.mdx
  packages/site-demo/content/product/components/generic-block/react/default.tsx
  packages/site-demo/content/product/components/generic-block/react/horizontal-alignment.tsx
  packages/site-demo/content/product/components/generic-block/react/sizes.tsx
  packages/site-demo/content/product/components/generic-block/react/vertical-alignment.tsx
  packages/site-demo/content/product/foundations/size/index.mdx
  packages/site-demo/plugins/lumx-mdx-preprocessor/mdx-prop-table.js
  packages/site-demo/src/components/content/Placeholder/index.tsx
Labels: need: review-frontend

#891 fix(inline-list): add listitem role to items
  CHANGELOG.md
  packages/lumx-react/src/components/inline-list/InlineList.tsx
  packages/site-demo/content/product/components/inline-list/index.mdx
  packages/site-demo/content/product/components/text/index.mdx
Labels: need: test

#895 docs(dropdown): added example of actions states
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/site-demo/content/product/components/dropdown/index.mdx
  packages/site-demo/content/product/components/dropdown/react/selects.tsx
  packages/site-demo/src/components/content/DemoBlock/DemoBlock.tsx
Labels: need: review-doc

#893 docs: document various component a11y concerns
  packages/lumx-react/src/stories/generated/Dropdown/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Dropdown/selects.tsx
  packages/site-demo/content/product/components/divider/index.mdx
  packages/site-demo/content/product/components/flag/index.mdx
  packages/site-demo/content/product/components/icon/index.mdx
  packages/site-demo/content/product/components/message/index.mdx
  packages/site-demo/content/product/components/tabs/index.mdx
  packages/site-demo/content/product/components/text/index.mdx
Labels: need: merge
