Repository lumapps/design-system, pull requests merged in 2022-03, with the labels that each got.

#784 chore(icon): add alt attribute
  CHANGELOG.md
  packages/lumx-react/src/components/icon/Icon.tsx
Labels: need: review-frontend

#785 chore(colors): scss primary & secondary variable in CSS
  CHANGELOG.md
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/style-dictionary/config/gen-scss-variables.js
  packages/lumx-core/style-dictionary/config/utils/_css-prefer-variable.js
  packages/lumx-core/style-dictionary/config/utils/_resolve-structure-alias.js
  packages/lumx-core/style-dictionary/properties/core/color.json
Labels: need: review-frontend

#788 release/v2.2.6
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#786 chore(slideshow): improve aria labels and focusable elements
  CHANGELOG.md
  packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.tsx
  packages/lumx-react/src/components/slideshow/SlideshowItem.tsx
  packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
Labels: need: merge

#787 chore(chromatic): change deploy label and remove label after deploy
  .eslintignore
  .gitattributes
  .github/pull_request_template.md
  .github/workflows/chromatic.yaml
  dev-packages/ga-remove-label/.gitignore
  dev-packages/ga-remove-label/action.yml
  dev-packages/ga-remove-label/dist/index.js
  dev-packages/ga-remove-label/index.js
  dev-packages/ga-remove-label/package.json
  package.json
  yarn.lock
Labels: need: review-frontend

#791 Chore: improve ESlint validation
  .eslintignore
  .eslintrc.json
  .github/workflows/lint.yml
  dev-packages/eslint-plugin-lumapps/index.js
  dev-packages/eslint-plugin-lumapps/package.json
  package.json
  packages/lumx-core/src/js/date-picker.ts
  packages/lumx-icons/v4-to-v5-aliases.d.ts
  packages/lumx-react/src/components/alert-dialog/AlertDialog.test.tsx
  packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.tsx
  packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
  packages/lumx-react/src/components/lightbox/Lightbox.stories.tsx
  packages/lumx-react/src/components/lightbox/Lightbox.tsx
  packages/lumx-react/src/components/notification/Notification.tsx
  packages/lumx-react/src/components/select/SelectMultiple.tsx
  packages/lumx-react/src/components/tabs/state.ts
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
  packages/lumx-react/src/utils/htmlDecode.ts
  packages/lumx-react/src/utils/index.tsx
  packages/lumx-react/src/utils/mergeRefs.ts
  packages/site-demo/content/product/components/list/react/clickable.tsx
  packages/site-demo/content/product/components/text-field/react/disabled.tsx
  packages/site-demo/content/product/components/thumbnail/react/ratios.tsx
  packages/site-demo/content/product/patterns/filter-and-sort/react/sorting.tsx
  yarn.lock
Labels: need: review-frontend

#792 chore(slideshow): create hook for slideshow controls
  CHANGELOG.md
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.tsx
  packages/lumx-react/src/hooks/useFocusWithin.ts
  packages/lumx-react/src/hooks/useSlideshowControls.ts
Labels: need: review-frontend

#789 chore(doc): add more doc on thumbnail loading and error state
  packages/lumx-react/src/stories/generated/Thumbnail/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Thumbnail/error-fallback.tsx
  packages/lumx-react/src/stories/generated/Thumbnail/error.tsx
  packages/lumx-react/src/stories/generated/Thumbnail/loading-error.tsx
  packages/lumx-react/src/stories/generated/Thumbnail/loading.tsx
  packages/site-demo/content/product/components/thumbnail/index.mdx
  packages/site-demo/content/product/components/thumbnail/react/error-fallback.tsx
  packages/site-demo/content/product/components/thumbnail/react/error.tsx
  packages/site-demo/content/product/components/thumbnail/react/loading.tsx
Labels: need: merge

#802 chore(slideshow): temporarily remove delayed visibility
  CHANGELOG.md
  packages/lumx-react/src/components/slideshow/Slides.tsx
  packages/lumx-react/src/components/slideshow/Slideshow.tsx
  packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
  packages/lumx-react/src/components/slideshow/SlideshowItem.tsx
  packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
  packages/lumx-react/src/hooks/useSlideshowControls.ts
Labels: need: review-frontend, need: review-design

#805 Fix/dropdown focus improvements
  CHANGELOG.md
  packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/lumx-react/src/components/autocomplete/__snapshots__/AutocompleteMultiple.test.tsx.snap
  packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
  packages/lumx-react/src/components/dropdown/Dropdown.tsx
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/components/list/List.tsx
  packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap
  packages/lumx-react/src/components/popover/Popover.tsx
  packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
  packages/lumx-react/src/components/select/__snapshots__/SelectMultiple.test.tsx.snap
Labels: need: test

#806 docs(toolbar): added file list toolbar example
  packages/site-demo/content/product/components/toolbar/index.mdx
  packages/site-demo/content/product/components/toolbar/react/file-widget.tsx
  packages/site-demo/src/style/layout/main/_main.scss
Labels: need: review-doc

#808 chore(release): release v2.2.12
  CHANGELOG.md
  dev-packages/eslint-plugin-lumapps/package.json
  dev-packages/ga-remove-label/package.json
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend
