Repository lumapps/design-system, pull requests merged in 2022-11, with the labels that each got.

#905 chore(ci): minor improvements
  .gitattributes
  .github/actions/remove-label/action.yml
  .github/actions/setup/action.yml
  .github/workflows/chromatic.yaml
  .github/workflows/dependencies.yml
  .github/workflows/release.yml
  .github/workflows/validate-pull-request.yml
  dev-packages/ga-remove-label/.gitignore
  dev-packages/ga-remove-label/action.yml
  dev-packages/ga-remove-label/dist/index.js
  dev-packages/ga-remove-label/index.js
  dev-packages/ga-remove-label/package.json
  yarn.lock
Labels: need: review-frontend

#907 refactor(jest): rework jest test configuration
  packages/lumx-react/jest/index.js
  packages/lumx-react/jest/transform.js
  packages/lumx-react/package.json
  packages/lumx-react/src/components/alert-dialog/__snapshots__/AlertDialog.test.tsx.snap
  packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/lumx-react/src/components/autocomplete/__snapshots__/AutocompleteMultiple.test.tsx.snap
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
  packages/lumx-react/src/components/button/__snapshots__/ButtonRoot.test.tsx.snap
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePicker.test.tsx.snap
  packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
  packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
  packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/lumx-react/src/components/flag/__snapshots__/Flag.test.tsx.snap
  packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
  packages/lumx-react/src/components/icon/__snapshots__/Icon.test.tsx.snap
  packages/lumx-react/src/components/image-block/__snapshots__/ImageBlock.test.tsx.snap
  packages/lumx-react/src/components/lightbox/__snapshots__/Lightbox.test.tsx.snap
  packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap
  packages/lumx-react/src/components/notification/__snapshots__/Notification.test.tsx.snap
  packages/lumx-react/src/components/popover/__snapshots__/Popover.test.tsx.snap
  packages/lumx-react/src/components/post-block/__snapshots__/PostBlock.test.tsx.snap
  packages/lumx-react/src/components/progress-tracker/__snapshots__/ProgressTracker.test.tsx.snap
  packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
  packages/lumx-react/src/components/select/__snapshots__/SelectMultiple.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonCircle.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonRectangle.test.tsx.snap
  packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonTypography.test.tsx.snap
  packages/lumx-react/src/components/slider/__snapshots__/Slider.test.tsx.snap
  packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
  packages/lumx-react/src/components/table/__snapshots__/Table.test.tsx.snap
  packages/lumx-react/src/components/text-field/TextField.test.tsx
  packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
  packages/lumx-react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
  packages/lumx-react/src/utils/focus/getFocusableElements.test.ts
  yarn.lock
Labels: need: review-frontend

#906 chore(autocomplete): forward textfield props
  CHANGELOG.md
  packages/lumx-react/src/components/autocomplete/Autocomplete.tsx
Labels: need: review-frontend

#913 chore: a11y improve & document checkbox, radiobutton & switch
  CHANGELOG.md
  packages/lumx-react/src/components/radio-button/RadioButton.tsx
  packages/lumx-react/src/components/radio-button/__snapshots__/RadioButton.test.tsx.snap
  packages/lumx-react/src/components/switch/Switch.tsx
  packages/lumx-react/src/components/switch/__snapshots__/Switch.test.tsx.snap
  packages/site-demo/content/product/components/checkbox/index.mdx
  packages/site-demo/content/product/components/radio-button/index.mdx
  packages/site-demo/content/product/components/switch/index.mdx
Labels: need: review-frontend

#908 chore(expansion-panel): a11y, documentation and test improvements
  CHANGELOG.md
  packages/lumx-react/src/components/expansion-panel/ExpansionPanel.test.tsx
  packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx
  packages/lumx-react/src/components/expansion-panel/__snapshots__/ExpansionPanel.test.tsx.snap
  packages/site-demo/content/product/components/expansion-panel/index.mdx
  packages/site-demo/content/product/components/expansion-panel/react/default.tsx
  packages/site-demo/content/product/components/expansion-panel/react/drag-handle.tsx
  packages/site-demo/content/product/components/expansion-panel/react/examples.tsx
  packages/site-demo/content/product/components/expansion-panel/react/trimmed.tsx
Labels: need: merge

#914 chore(dialog): rework unmount to use CSS transition instead of timeout
  CHANGELOG.md
  packages/lumx-react/src/components/dialog/Dialog.tsx
  packages/lumx-react/src/components/lightbox/Lightbox.tsx
  packages/lumx-react/src/components/notification/Notification.tsx
  packages/lumx-react/src/hooks/useDelayedVisibility.tsx
  packages/lumx-react/src/hooks/useTransitionVisibility.ts
  packages/lumx-react/src/utils/userHasReducedMotion.ts
Labels: need: dev-frontend

#921 chore(ci): add release note workflow
  .github/actions/release-note/action.yml
  .github/actions/release-note/index.js
  .github/workflows/release.yml
  configs/path.js
Labels: need: review-frontend

#923 chore(ci): fix release-note workflow
  .github/actions/release-note/action.yml
  .github/actions/release-note/index.js
Labels: need: merge

#924 feat(button): make text truncate work with the button component
  CHANGELOG.md
  packages/lumx-react/src/components/button/Button.stories.tsx
  packages/lumx-react/src/components/button/Button.tsx
Labels: need: review-frontend
