Repository lumapps/design-system, pull requests merged in 2022-01, with the labels that each got.

#754 docs(list): updated documentations
  .vscode/tasks.json
  .vscode/tasks.json.old
  packages/lumx-react/src/stories/generated/List/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/List/paddings.tsx
  packages/site-demo/content/product/components/list/index.mdx
  packages/site-demo/content/product/components/list/react/clickable.tsx
  packages/site-demo/content/product/components/list/react/paddings.tsx
Labels: need: review-doc

#757 chore(storybook): fix dark theme switcher & chromatic date override
  package.json
  packages/lumx-react/src/stories/generated/List/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/List/clickable.tsx
  packages/lumx-react/storybook/story-block/StoryBlock.tsx
  packages/lumx-react/storybook/story-block/decorator.jsx
Labels: need: review-frontend

#758 chore(color): always use colors css variables
  CHANGELOG.md
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/src/scss/core/color/_functions.scss
  packages/lumx-core/style-dictionary/config/_transform-group.js
  packages/lumx-core/style-dictionary/config/gen-css-variables.js
  packages/lumx-core/style-dictionary/config/gen-scss-variables.js
  packages/lumx-core/style-dictionary/config/gen-ts-variables.js
  packages/lumx-core/style-dictionary/config/utils/_color-attributes.js
  packages/lumx-core/style-dictionary/config/utils/_color-opacity.js
  packages/lumx-core/style-dictionary/config/utils/_color-rgba-value.js
  packages/lumx-core/style-dictionary/config/utils/_css-prefer-variable.js
  packages/lumx-core/style-dictionary/config/utils/_css-transform-group.js
  packages/lumx-core/style-dictionary/config/utils/_prettier-ts.js
  packages/lumx-core/style-dictionary/config/utils/_resolve-structure-alias.js
  packages/lumx-core/style-dictionary/properties/components/button.json
  packages/lumx-core/style-dictionary/properties/components/navigation.json
  packages/lumx-core/style-dictionary/properties/components/tabs.json
  packages/lumx-core/style-dictionary/properties/components/text-field.json
  packages/lumx-core/style-dictionary/properties/core/color.json
  packages/site-demo/content/product/components/chip/react/filter.tsx
  packages/site-demo/src/utils/hooks/useThemeColorVariants.ts
Labels: need: review-frontend

#709 docs(thumbnail-update): added ratio and states explanations
  packages/site-demo/content/product/components/thumbnail/index.mdx
  packages/site-demo/content/product/components/thumbnail/react/loading-error.tsx
  packages/site-demo/content/product/components/thumbnail/react/ratios.tsx
Labels: need: merge

#764 feat(a11y): fix avatar and userblock link/button a11y
  CHANGELOG.md
  packages/lumx-core/src/scss/components/user-block/_index.scss
  packages/lumx-react/src/components/avatar/Avatar.stories.tsx
  packages/lumx-react/src/components/avatar/Avatar.tsx
  packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
  packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.test.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
  packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
  packages/lumx-react/src/stories/utils/CustomLink.tsx
Labels: need: merge

#767 fix(tooltip): fix tooltip on element using function ref
  CHANGELOG.md
  packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx
  packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Labels: need: merge

#759 docs(form-validation): fix wrong text and image
  packages/site-demo/content/product/patterns/form-validation/index.mdx
Labels: need: merge

#756 docs(flag): added documentation page
  packages/site-demo/content/product/components/flag/index.mdx
  packages/site-demo/content/product/components/flag/react/.gitkeep
  packages/site-demo/content/product/components/flag/react/flag.tsx
Labels: need: merge

#755 Docs/badge : added section about colors
  packages/site-demo/content/product/components/badge/index.mdx
  packages/site-demo/content/product/components/badge/react/colors.tsx
Labels: need: merge

#769 fix/thumbnail small image with size
  CHANGELOG.md
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
  packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
  packages/lumx-react/src/stories/generated/Badge/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Badge/colors.tsx
  packages/lumx-react/src/stories/generated/Flag/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Flag/flag.tsx
Labels: need: review-frontend

#771 chore(release): release v2.2.1
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend

#773 chore(release): release v2.2.2
  CHANGELOG.md
  lerna.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-icons/package.json
  packages/lumx-react/package.json
  packages/site-demo/package.json
  packages/yo-generators/package.json
  yarn.lock
Labels: need: review-frontend, need: merge
