Repository lumapps/design-system, pull requests merged in 2023-06, with the labels that each got.

#983 fix(textfield): focus the input on clear button click
  CHANGELOG.md
  packages/lumx-react/src/components/text-field/TextField.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: test

#978 chore(storybook): update to storybook v7 with vite & internally update React v17
  package.json
  packages/lumx-angularjs/package.json
  packages/lumx-core/package.json
  packages/lumx-react/.storybook/generate-demo-stories.js
  packages/lumx-react/.storybook/main.ts
  packages/lumx-react/.storybook/postcss.config.js
  packages/lumx-react/.storybook/preview-head.html
  packages/lumx-react/.storybook/preview.ts
  packages/lumx-react/.storybook/story-block/StoryBlock.tsx
  packages/lumx-react/.storybook/story-block/decorator.jsx
  packages/lumx-react/.storybook/story-block/index.scss
  packages/lumx-react/.storybook/story-block/toggleMaterialTheme.tsx
  packages/lumx-react/package.json
  packages/lumx-react/src/components/grid-column/GridColumn.stories.tsx
  packages/lumx-react/storybook/.gitignore
  packages/lumx-react/storybook/build
  packages/lumx-react/storybook/main.js
  packages/lumx-react/storybook/package.json
  packages/lumx-react/storybook/preview.js
  packages/lumx-react/storybook/start
  packages/lumx-react/storybook/yarn.lock
  packages/site-demo/package.json
  yarn.lock
Labels: need: review-frontend

#989 chore(demo): fix docker config
  .dockerignore
  .github/workflows/release-build-site.yml
  .github/workflows/release-deploy-chromatic.yaml
  .github/workflows/release-github-release-note.yml
  Dockerfile
Labels: need: review-frontend

#963 Feat/thumbnail aspect ratio
  CHANGELOG.md
  packages/lumx-core/src/scss/components/mosaic/_index.scss
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
  packages/lumx-core/src/scss/components/thumbnail/_variables.scss
  packages/lumx-react/src/components/index.ts
Labels: need: test

#996 fix(autocomplete): focus text field on clear button clicked
  CHANGELOG.md
  packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx
  packages/lumx-react/src/components/text-field/TextField.tsx
Labels: need: merge

#998 docs(progress): add accessibility concerns section ARCH-44
  packages/site-demo/content/product/components/progress/index.mdx
Labels: need: review-frontend

#997 fix(side-navigation): improve and document a11y ARCH-48
  CHANGELOG.md
  packages/lumx-core/src/scss/components/side-navigation/_mixins.scss
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx
  packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
  packages/lumx-react/src/utils/renderButtonOrLink.tsx
  packages/lumx-react/src/utils/renderLink.tsx
  packages/site-demo/content/product/components/side-navigation/index.mdx
Labels: need: test

#999 docs(image-block): add accessibility concerns section ARCH-35
  packages/site-demo/content/product/components/image-block/index.mdx
  packages/site-demo/content/product/components/image-block/react/default.tsx
Labels: need: merge
