Repository lumapps/design-system, pull requests merged in 2024-10, with the labels that each got.

#1193 chore(tooltip): update tooltip position on open
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
Labels: need: review-frontend

#1194 feat(tooltip): increment z-index above popover default z-index
  CHANGELOG.md
  packages/lumx-react/src/components/popover/Popover.tsx
  packages/lumx-react/src/components/popover/constants.ts
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
  packages/lumx-react/src/components/tooltip/constants.ts
Labels: need: review-frontend

#1196 chore(data-picker): fix non alpha-numeric formatted year
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
Labels: need: review-frontend

#1199 feat(tooltip): use standard visually-hidden class in closeMode=hide
  CHANGELOG.md
  packages/lumx-core/src/scss/components/tooltip/_index.scss
  packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
  packages/lumx-react/src/components/tooltip/Tooltip.test.tsx
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
  packages/lumx-react/src/constants.ts
Labels: need: review-frontend

#1203 docs(mosaic): removed broken lightboxes on mosaic demos.
  CHANGELOG.md
  packages/lumx-react/src/stories/generated/Mosaic/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Mosaic/clickable.tsx
  packages/site-demo/content/product/components/image-lightbox/react/default.tsx
  packages/site-demo/content/product/components/mosaic/index.mdx
  packages/site-demo/content/product/components/mosaic/react/clickable.tsx
  packages/site-demo/content/product/components/mosaic/react/four-images.tsx
  packages/site-demo/content/product/components/mosaic/react/more-images.tsx
  packages/site-demo/content/product/components/mosaic/react/three-images.tsx
  packages/site-demo/content/product/components/mosaic/react/two-images.tsx
Labels: need: review-doc

#1205 feat(badge): add a wrapper to enable adding a badge to any component
  CHANGELOG.md
  packages/lumx-core/src/scss/components/badge/_index.scss
  packages/lumx-react/src/components/badge/BadgeWrapper.stories.tsx
  packages/lumx-react/src/components/badge/BadgeWrapper.test.tsx
  packages/lumx-react/src/components/badge/BadgeWrapper.tsx
  packages/lumx-react/src/components/badge/index.ts
Labels: need: test
