Repository lumapps/design-system, pull requests merged in 2024-03, with the labels that each got.

#1101 fix(chip-group): use gap instead of margin and depreciate the align property
  CHANGELOG.md
  packages/lumx-core/src/scss/components/chip/_index.scss
  packages/lumx-core/src/scss/components/text-field/_index.scss
  packages/lumx-core/src/scss/components/text-field/_mixins.scss
  packages/lumx-react/src/components/chip/ChipGroup.stories.tsx
  packages/lumx-react/src/components/chip/ChipGroup.test.tsx
  packages/lumx-react/src/components/chip/ChipGroup.tsx
Labels: need: test

#1105 fix(color-a11y): changed red and green, changed low and medium text color
  CHANGELOG.md
  packages/lumx-core/src/css/design-tokens.css
  packages/lumx-core/src/js/constants/design-tokens.ts
  packages/lumx-core/src/scss/_design-tokens.scss
  packages/lumx-core/src/scss/core/state/_mixins.scss
  packages/lumx-core/style-dictionary/properties/core/color.json
Labels: need: review-integration, need: merge

#1104 feat(date-picker): add text field for year
  CHANGELOG.md
  packages/lumx-core/src/scss/components/date-picker/_index.scss
  packages/lumx-react/src/components/date-picker/DatePicker.test.tsx
  packages/lumx-react/src/components/date-picker/DatePicker.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx
  packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
  packages/lumx-react/src/components/date-picker/DatePickerField.test.tsx
  packages/lumx-react/src/utils/date/getYearDisplayName.test.ts
  packages/lumx-react/src/utils/date/getYearDisplayName.ts
Labels: need: merge

#1110 feat(message): add a close button to the message component
  CHANGELOG.md
  packages/lumx-core/src/scss/components/message/_index.scss
  packages/lumx-react/src/components/message/Message.stories.tsx
  packages/lumx-react/src/components/message/Message.test.tsx
  packages/lumx-react/src/components/message/Message.tsx
  packages/lumx-react/src/stories/generated/Message/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/Message/closable.tsx
  packages/site-demo/content/product/components/message/index.mdx
  packages/site-demo/content/product/components/message/react/closable.tsx
Labels: need: merge

#1107 feat(dialog): make dialog full size on mobile
  CHANGELOG.md
  packages/lumx-core/src/scss/components/dialog/_index.scss
  packages/lumx-core/src/scss/components/dialog/_variables.scss
Labels: need: merge

#1115 chore(popover): allow to set the element to set a focus trap on
  CHANGELOG.md
  packages/lumx-react/src/components/popover/Popover.tsx
  packages/lumx-react/src/hooks/useFocusTrap.ts
  packages/lumx-react/src/utils/focus/getFirstAndLastFocusable.ts
  packages/lumx-react/src/utils/focus/getFocusableElements.ts
Labels: need: review-frontend
