Repository lumapps/design-system, pull requests merged in 2024-01, with the labels that each got.

#1037 feat(text): add whiteSpace support
  CHANGELOG.md
  packages/lumx-core/src/scss/components/text/_index.scss
  packages/lumx-react/src/components/index.ts
  packages/lumx-react/src/components/text/Text.stories.tsx
  packages/lumx-react/src/components/text/Text.test.tsx
  packages/lumx-react/src/components/text/Text.tsx
Labels: need: dev-frontend

#1063 chore(tooltip): fix escape key handler only when open
  packages/lumx-react/src/components/tooltip/Tooltip.test.tsx
  packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
Labels: need: review-frontend

#1071 fix(avatar): fix Chrome behavior when downscaling avatar
  CHANGELOG.md
  packages/lumx-core/src/scss/components/thumbnail/_index.scss
Labels: need: test, need: review-frontend, need: review-integration
