Repository lumapps/design-system, pull requests merged in 2024-09, with the labels that each got.

#1176 feat(user-block xs): added a size XS to usr block
  CHANGELOG.md
  packages/lumx-core/src/scss/components/user-block/_index.scss
  packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
  packages/lumx-react/src/components/user-block/UserBlock.tsx
  packages/lumx-react/src/stories/generated/UserBlock/Demos.stories.tsx
  packages/lumx-react/src/stories/generated/UserBlock/size-xs.tsx
  packages/site-demo/content/product/components/user-block/index.mdx
  packages/site-demo/content/product/components/user-block/react/size-xs.tsx
Labels: need: merge

#1179 chore(workflow): fix demo site docker tags
  .github/workflows/release-publish.yaml
Labels: need: review-frontend

#1180 fix(tooltip): fix re-render errors when removing the label
  CHANGELOG.md
  packages/lumx-react/src/components/tooltip/Tooltip.tsx
  packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Labels: need: test

#1183 fix(image-lightbox): fix zoom on mouse wheel cursor position
  CHANGELOG.md
  packages/lumx-react/src/components/image-lightbox/internal/usePointerZoom.ts
Labels: need: review-frontend

#1187 fix(slideshow-a11y): Changed active pagination item width for a11y improvement
  CHANGELOG.md
  packages/lumx-core/src/scss/components/slideshow/_index.scss
Labels: need: merge
